package sharedfeed

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// WriteDocument: atomic-write the canonical feed JSON for the browse page
// (= /admin/shared-feed/) to read and render.  Outputs shared-feed-doc.json in
// the same dir as WriteMapFiles.  Always overwrites even on empty doc (= the
// browse page renders "entry=0").
func WriteDocument(doc FeedDocument, dir string) error {
	if dir == "" {
		return nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	body, err := json.Marshal(doc)
	if err != nil {
		return err
	}
	path := filepath.Join(dir, "shared-feed-doc.json")
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, body, 0o644); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}

// ReadDocument: reads the JSON written by WriteDocument.  Returns an empty
// doc if the file does not exist.
func ReadDocument(dir string) (FeedDocument, error) {
	if dir == "" {
		return FeedDocument{}, nil
	}
	body, err := os.ReadFile(filepath.Join(dir, "shared-feed-doc.json"))
	if err != nil {
		if os.IsNotExist(err) {
			return FeedDocument{}, nil
		}
		return FeedDocument{}, err
	}
	var doc FeedDocument
	if err := json.Unmarshal(body, &doc); err != nil {
		return FeedDocument{}, err
	}
	return doc, nil
}

// WriteMapFiles: split feed entries across 3 nginx map snippets and atomic-write.
//
// Output:
//
//	shared-feed-ipja4.map  ← match=ip_ja4  : `"<ip>:<ja4>" 1;`
//	shared-feed-ja4.map    ← match=ja4_only: `"<ja4>"      1;`
//	shared-feed-ip.map     ← match=ip_only : `"<ip>"       1;`
//
// nginx includes them via map ${key} ${var} { default 0; include ...; } to
// drive the hit check.
//
// Always generates all 3 files even on empty feed (= avoids nginx startup
// failure on missing include).
func WriteMapFiles(doc FeedDocument, dir string) error {
	if dir == "" {
		return fmt.Errorf("WriteMapFiles: empty dir")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}

	now := time.Now().Unix()

	var ipja4, ja4, ip []string
	for _, e := range doc.Entries {
		if e.ExpiresAt > 0 && e.ExpiresAt < now {
			continue
		}
		ipv := strings.TrimSpace(e.IP)
		j := strings.TrimSpace(e.JA4)
		switch e.Match {
		case MatchIPJA4:
			if ipv == "" || j == "" {
				continue
			}
			ipja4 = append(ipja4, fmt.Sprintf("%q 1;", ipv+":"+j))
		case MatchJA4:
			if j == "" {
				continue
			}
			ja4 = append(ja4, fmt.Sprintf("%q 1;", j))
		case MatchIPOnly:
			if ipv == "" {
				continue
			}
			ip = append(ip, fmt.Sprintf("%q 1;", ipv))
		}
	}
	sort.Strings(ipja4)
	sort.Strings(ja4)
	sort.Strings(ip)

	if err := atomicWriteLines(filepath.Join(dir, "shared-feed-ipja4.map"), ipja4); err != nil {
		return err
	}
	if err := atomicWriteLines(filepath.Join(dir, "shared-feed-ja4.map"), ja4); err != nil {
		return err
	}
	if err := atomicWriteLines(filepath.Join(dir, "shared-feed-ip.map"), ip); err != nil {
		return err
	}
	return nil
}

// atomicWriteLines: atomic via tmp file + rename.  Sorted duplicates are uniq'd.
func atomicWriteLines(path string, lines []string) error {
	var b strings.Builder
	b.WriteString("# generated by unmask-admin sharedfeed. DO NOT EDIT.\n")
	last := ""
	for _, l := range lines {
		if l == last {
			continue
		}
		b.WriteString(l)
		b.WriteByte('\n')
		last = l
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("rename %s → %s: %w", tmp, path, err)
	}
	return nil
}
