-- 0032 fingerprint index on the event table.
--
-- What a fingerprint ban would hit -- which addresses completed the challenge
-- with that JA4 in the last seven days -- is asked for every fingerprint
-- candidate the advisor sends to the model, and again by the ban dialog
-- before a human decides.  unmask_event had no index on ja4, so those reads
-- were pinned to the date index and walked the whole retention window; with
-- the default seven-day retention that window is every row in the table.
--
-- The column order is what makes it work.  Indexing (ja4, date_created) alone
-- does not help a consultation: the fingerprints worth asking about are the
-- busiest ones on the node, so narrowing to them still leaves most of the
-- table.  What separates the answer from the rest is the phase -- completions
-- are a small fraction of what a busy fingerprint does -- so phase comes
-- second, and the read seeks straight to the rows that answer the question.
CREATE INDEX IF NOT EXISTS idx_unmask_event_ja4_phase ON unmask_event(ja4, phase, date_created);
