// Package ipgeo: country master list for the per-country rule UI.
//
// Source: ISO 3166-1 alpha-2 (with Kosovo "XK" added as a de-facto code).
// Names are kept short for table display.  Japanese names follow the
// Foreign Ministry / common-news convention rather than the rarer ISO
// transliteration (= "イギリス" not "連合王国" etc.).
package ipgeo

// Country holds the display names for one ISO 3166-1 alpha-2 code.
type Country struct {
	Code   string // upper-case ISO 3166-1 alpha-2
	NameEN string
	NameJP string
}

// Countries: the full master list, code -> Country.  Used to power the
// per-country rule UI's autocomplete + label rendering.
var Countries = map[string]Country{
	"AD": {"AD", "Andorra", "アンドラ"},
	"AE": {"AE", "United Arab Emirates", "アラブ首長国連邦"},
	"AF": {"AF", "Afghanistan", "アフガニスタン"},
	"AG": {"AG", "Antigua and Barbuda", "アンティグア・バーブーダ"},
	"AI": {"AI", "Anguilla", "アンギラ"},
	"AL": {"AL", "Albania", "アルバニア"},
	"AM": {"AM", "Armenia", "アルメニア"},
	"AO": {"AO", "Angola", "アンゴラ"},
	"AQ": {"AQ", "Antarctica", "南極"},
	"AR": {"AR", "Argentina", "アルゼンチン"},
	"AS": {"AS", "American Samoa", "アメリカ領サモア"},
	"AT": {"AT", "Austria", "オーストリア"},
	"AU": {"AU", "Australia", "オーストラリア"},
	"AW": {"AW", "Aruba", "アルバ"},
	"AX": {"AX", "Åland Islands", "オーランド諸島"},
	"AZ": {"AZ", "Azerbaijan", "アゼルバイジャン"},
	"BA": {"BA", "Bosnia and Herzegovina", "ボスニア・ヘルツェゴビナ"},
	"BB": {"BB", "Barbados", "バルバドス"},
	"BD": {"BD", "Bangladesh", "バングラデシュ"},
	"BE": {"BE", "Belgium", "ベルギー"},
	"BF": {"BF", "Burkina Faso", "ブルキナファソ"},
	"BG": {"BG", "Bulgaria", "ブルガリア"},
	"BH": {"BH", "Bahrain", "バーレーン"},
	"BI": {"BI", "Burundi", "ブルンジ"},
	"BJ": {"BJ", "Benin", "ベナン"},
	"BL": {"BL", "Saint Barthélemy", "サン・バルテルミー"},
	"BM": {"BM", "Bermuda", "バミューダ"},
	"BN": {"BN", "Brunei", "ブルネイ"},
	"BO": {"BO", "Bolivia", "ボリビア"},
	"BQ": {"BQ", "Caribbean Netherlands", "オランダ領カリブ"},
	"BR": {"BR", "Brazil", "ブラジル"},
	"BS": {"BS", "Bahamas", "バハマ"},
	"BT": {"BT", "Bhutan", "ブータン"},
	"BV": {"BV", "Bouvet Island", "ブーベ島"},
	"BW": {"BW", "Botswana", "ボツワナ"},
	"BY": {"BY", "Belarus", "ベラルーシ"},
	"BZ": {"BZ", "Belize", "ベリーズ"},
	"CA": {"CA", "Canada", "カナダ"},
	"CC": {"CC", "Cocos (Keeling) Islands", "ココス諸島"},
	"CD": {"CD", "Congo (DRC)", "コンゴ民主共和国"},
	"CF": {"CF", "Central African Republic", "中央アフリカ共和国"},
	"CG": {"CG", "Congo (Republic)", "コンゴ共和国"},
	"CH": {"CH", "Switzerland", "スイス"},
	"CI": {"CI", "Côte d'Ivoire", "コートジボワール"},
	"CK": {"CK", "Cook Islands", "クック諸島"},
	"CL": {"CL", "Chile", "チリ"},
	"CM": {"CM", "Cameroon", "カメルーン"},
	"CN": {"CN", "China", "中国"},
	"CO": {"CO", "Colombia", "コロンビア"},
	"CR": {"CR", "Costa Rica", "コスタリカ"},
	"CU": {"CU", "Cuba", "キューバ"},
	"CV": {"CV", "Cape Verde", "カーボベルデ"},
	"CW": {"CW", "Curaçao", "キュラソー"},
	"CX": {"CX", "Christmas Island", "クリスマス島"},
	"CY": {"CY", "Cyprus", "キプロス"},
	"CZ": {"CZ", "Czechia", "チェコ"},
	"DE": {"DE", "Germany", "ドイツ"},
	"DJ": {"DJ", "Djibouti", "ジブチ"},
	"DK": {"DK", "Denmark", "デンマーク"},
	"DM": {"DM", "Dominica", "ドミニカ国"},
	"DO": {"DO", "Dominican Republic", "ドミニカ共和国"},
	"DZ": {"DZ", "Algeria", "アルジェリア"},
	"EC": {"EC", "Ecuador", "エクアドル"},
	"EE": {"EE", "Estonia", "エストニア"},
	"EG": {"EG", "Egypt", "エジプト"},
	"EH": {"EH", "Western Sahara", "西サハラ"},
	"ER": {"ER", "Eritrea", "エリトリア"},
	"ES": {"ES", "Spain", "スペイン"},
	"ET": {"ET", "Ethiopia", "エチオピア"},
	"FI": {"FI", "Finland", "フィンランド"},
	"FJ": {"FJ", "Fiji", "フィジー"},
	"FK": {"FK", "Falkland Islands", "フォークランド諸島"},
	"FM": {"FM", "Micronesia", "ミクロネシア連邦"},
	"FO": {"FO", "Faroe Islands", "フェロー諸島"},
	"FR": {"FR", "France", "フランス"},
	"GA": {"GA", "Gabon", "ガボン"},
	"GB": {"GB", "United Kingdom", "イギリス"},
	"GD": {"GD", "Grenada", "グレナダ"},
	"GE": {"GE", "Georgia", "ジョージア"},
	"GF": {"GF", "French Guiana", "フランス領ギアナ"},
	"GG": {"GG", "Guernsey", "ガーンジー"},
	"GH": {"GH", "Ghana", "ガーナ"},
	"GI": {"GI", "Gibraltar", "ジブラルタル"},
	"GL": {"GL", "Greenland", "グリーンランド"},
	"GM": {"GM", "Gambia", "ガンビア"},
	"GN": {"GN", "Guinea", "ギニア"},
	"GP": {"GP", "Guadeloupe", "グアドループ"},
	"GQ": {"GQ", "Equatorial Guinea", "赤道ギニア"},
	"GR": {"GR", "Greece", "ギリシャ"},
	"GS": {"GS", "South Georgia", "サウスジョージア諸島"},
	"GT": {"GT", "Guatemala", "グアテマラ"},
	"GU": {"GU", "Guam", "グアム"},
	"GW": {"GW", "Guinea-Bissau", "ギニアビサウ"},
	"GY": {"GY", "Guyana", "ガイアナ"},
	"HK": {"HK", "Hong Kong", "香港"},
	"HM": {"HM", "Heard Island", "ハード島"},
	"HN": {"HN", "Honduras", "ホンジュラス"},
	"HR": {"HR", "Croatia", "クロアチア"},
	"HT": {"HT", "Haiti", "ハイチ"},
	"HU": {"HU", "Hungary", "ハンガリー"},
	"ID": {"ID", "Indonesia", "インドネシア"},
	"IE": {"IE", "Ireland", "アイルランド"},
	"IL": {"IL", "Israel", "イスラエル"},
	"IM": {"IM", "Isle of Man", "マン島"},
	"IN": {"IN", "India", "インド"},
	"IO": {"IO", "British Indian Ocean Territory", "英領インド洋地域"},
	"IQ": {"IQ", "Iraq", "イラク"},
	"IR": {"IR", "Iran", "イラン"},
	"IS": {"IS", "Iceland", "アイスランド"},
	"IT": {"IT", "Italy", "イタリア"},
	"JE": {"JE", "Jersey", "ジャージー"},
	"JM": {"JM", "Jamaica", "ジャマイカ"},
	"JO": {"JO", "Jordan", "ヨルダン"},
	"JP": {"JP", "Japan", "日本"},
	"KE": {"KE", "Kenya", "ケニア"},
	"KG": {"KG", "Kyrgyzstan", "キルギス"},
	"KH": {"KH", "Cambodia", "カンボジア"},
	"KI": {"KI", "Kiribati", "キリバス"},
	"KM": {"KM", "Comoros", "コモロ"},
	"KN": {"KN", "Saint Kitts and Nevis", "セントクリストファー・ネイビス"},
	"KP": {"KP", "Korea (North)", "北朝鮮"},
	"KR": {"KR", "Korea (South)", "韓国"},
	"KW": {"KW", "Kuwait", "クウェート"},
	"KY": {"KY", "Cayman Islands", "ケイマン諸島"},
	"KZ": {"KZ", "Kazakhstan", "カザフスタン"},
	"LA": {"LA", "Laos", "ラオス"},
	"LB": {"LB", "Lebanon", "レバノン"},
	"LC": {"LC", "Saint Lucia", "セントルシア"},
	"LI": {"LI", "Liechtenstein", "リヒテンシュタイン"},
	"LK": {"LK", "Sri Lanka", "スリランカ"},
	"LR": {"LR", "Liberia", "リベリア"},
	"LS": {"LS", "Lesotho", "レソト"},
	"LT": {"LT", "Lithuania", "リトアニア"},
	"LU": {"LU", "Luxembourg", "ルクセンブルク"},
	"LV": {"LV", "Latvia", "ラトビア"},
	"LY": {"LY", "Libya", "リビア"},
	"MA": {"MA", "Morocco", "モロッコ"},
	"MC": {"MC", "Monaco", "モナコ"},
	"MD": {"MD", "Moldova", "モルドバ"},
	"ME": {"ME", "Montenegro", "モンテネグロ"},
	"MF": {"MF", "Saint Martin (French)", "サン・マルタン"},
	"MG": {"MG", "Madagascar", "マダガスカル"},
	"MH": {"MH", "Marshall Islands", "マーシャル諸島"},
	"MK": {"MK", "North Macedonia", "北マケドニア"},
	"ML": {"ML", "Mali", "マリ"},
	"MM": {"MM", "Myanmar", "ミャンマー"},
	"MN": {"MN", "Mongolia", "モンゴル"},
	"MO": {"MO", "Macao", "マカオ"},
	"MP": {"MP", "Northern Mariana Islands", "北マリアナ諸島"},
	"MQ": {"MQ", "Martinique", "マルティニーク"},
	"MR": {"MR", "Mauritania", "モーリタニア"},
	"MS": {"MS", "Montserrat", "モントセラト"},
	"MT": {"MT", "Malta", "マルタ"},
	"MU": {"MU", "Mauritius", "モーリシャス"},
	"MV": {"MV", "Maldives", "モルディブ"},
	"MW": {"MW", "Malawi", "マラウイ"},
	"MX": {"MX", "Mexico", "メキシコ"},
	"MY": {"MY", "Malaysia", "マレーシア"},
	"MZ": {"MZ", "Mozambique", "モザンビーク"},
	"NA": {"NA", "Namibia", "ナミビア"},
	"NC": {"NC", "New Caledonia", "ニューカレドニア"},
	"NE": {"NE", "Niger", "ニジェール"},
	"NF": {"NF", "Norfolk Island", "ノーフォーク島"},
	"NG": {"NG", "Nigeria", "ナイジェリア"},
	"NI": {"NI", "Nicaragua", "ニカラグア"},
	"NL": {"NL", "Netherlands", "オランダ"},
	"NO": {"NO", "Norway", "ノルウェー"},
	"NP": {"NP", "Nepal", "ネパール"},
	"NR": {"NR", "Nauru", "ナウル"},
	"NU": {"NU", "Niue", "ニウエ"},
	"NZ": {"NZ", "New Zealand", "ニュージーランド"},
	"OM": {"OM", "Oman", "オマーン"},
	"PA": {"PA", "Panama", "パナマ"},
	"PE": {"PE", "Peru", "ペルー"},
	"PF": {"PF", "French Polynesia", "フランス領ポリネシア"},
	"PG": {"PG", "Papua New Guinea", "パプアニューギニア"},
	"PH": {"PH", "Philippines", "フィリピン"},
	"PK": {"PK", "Pakistan", "パキスタン"},
	"PL": {"PL", "Poland", "ポーランド"},
	"PM": {"PM", "Saint Pierre and Miquelon", "サンピエール島・ミクロン島"},
	"PN": {"PN", "Pitcairn Islands", "ピトケアン諸島"},
	"PR": {"PR", "Puerto Rico", "プエルトリコ"},
	"PS": {"PS", "Palestine", "パレスチナ"},
	"PT": {"PT", "Portugal", "ポルトガル"},
	"PW": {"PW", "Palau", "パラオ"},
	"PY": {"PY", "Paraguay", "パラグアイ"},
	"QA": {"QA", "Qatar", "カタール"},
	"RE": {"RE", "Réunion", "レユニオン"},
	"RO": {"RO", "Romania", "ルーマニア"},
	"RS": {"RS", "Serbia", "セルビア"},
	"RU": {"RU", "Russia", "ロシア"},
	"RW": {"RW", "Rwanda", "ルワンダ"},
	"SA": {"SA", "Saudi Arabia", "サウジアラビア"},
	"SB": {"SB", "Solomon Islands", "ソロモン諸島"},
	"SC": {"SC", "Seychelles", "セーシェル"},
	"SD": {"SD", "Sudan", "スーダン"},
	"SE": {"SE", "Sweden", "スウェーデン"},
	"SG": {"SG", "Singapore", "シンガポール"},
	"SH": {"SH", "Saint Helena", "セントヘレナ"},
	"SI": {"SI", "Slovenia", "スロベニア"},
	"SJ": {"SJ", "Svalbard and Jan Mayen", "スバールバル諸島・ヤンマイエン島"},
	"SK": {"SK", "Slovakia", "スロバキア"},
	"SL": {"SL", "Sierra Leone", "シエラレオネ"},
	"SM": {"SM", "San Marino", "サンマリノ"},
	"SN": {"SN", "Senegal", "セネガル"},
	"SO": {"SO", "Somalia", "ソマリア"},
	"SR": {"SR", "Suriname", "スリナム"},
	"SS": {"SS", "South Sudan", "南スーダン"},
	"ST": {"ST", "São Tomé and Príncipe", "サントメ・プリンシペ"},
	"SV": {"SV", "El Salvador", "エルサルバドル"},
	"SX": {"SX", "Sint Maarten (Dutch)", "シント・マールテン"},
	"SY": {"SY", "Syria", "シリア"},
	"SZ": {"SZ", "Eswatini", "エスワティニ"},
	"TC": {"TC", "Turks and Caicos Islands", "タークス・カイコス諸島"},
	"TD": {"TD", "Chad", "チャド"},
	"TF": {"TF", "French Southern Territories", "仏領南方"},
	"TG": {"TG", "Togo", "トーゴ"},
	"TH": {"TH", "Thailand", "タイ"},
	"TJ": {"TJ", "Tajikistan", "タジキスタン"},
	"TK": {"TK", "Tokelau", "トケラウ"},
	"TL": {"TL", "Timor-Leste", "東ティモール"},
	"TM": {"TM", "Turkmenistan", "トルクメニスタン"},
	"TN": {"TN", "Tunisia", "チュニジア"},
	"TO": {"TO", "Tonga", "トンガ"},
	"TR": {"TR", "Turkey", "トルコ"},
	"TT": {"TT", "Trinidad and Tobago", "トリニダード・トバゴ"},
	"TV": {"TV", "Tuvalu", "ツバル"},
	"TW": {"TW", "Taiwan", "台湾"},
	"TZ": {"TZ", "Tanzania", "タンザニア"},
	"UA": {"UA", "Ukraine", "ウクライナ"},
	"UG": {"UG", "Uganda", "ウガンダ"},
	"UM": {"UM", "U.S. Outlying Islands", "合衆国領有小離島"},
	"US": {"US", "United States", "アメリカ合衆国"},
	"UY": {"UY", "Uruguay", "ウルグアイ"},
	"UZ": {"UZ", "Uzbekistan", "ウズベキスタン"},
	"VA": {"VA", "Vatican City", "バチカン"},
	"VC": {"VC", "Saint Vincent and the Grenadines", "セントビンセント・グレナディーン"},
	"VE": {"VE", "Venezuela", "ベネズエラ"},
	"VG": {"VG", "British Virgin Islands", "英領ヴァージン諸島"},
	"VI": {"VI", "U.S. Virgin Islands", "米領ヴァージン諸島"},
	"VN": {"VN", "Vietnam", "ベトナム"},
	"VU": {"VU", "Vanuatu", "バヌアツ"},
	"WF": {"WF", "Wallis and Futuna", "ウォリス・フツナ"},
	"WS": {"WS", "Samoa", "サモア"},
	"XK": {"XK", "Kosovo", "コソボ"},
	"YE": {"YE", "Yemen", "イエメン"},
	"YT": {"YT", "Mayotte", "マヨット"},
	"ZA": {"ZA", "South Africa", "南アフリカ"},
	"ZM": {"ZM", "Zambia", "ザンビア"},
	"ZW": {"ZW", "Zimbabwe", "ジンバブエ"},
}

// IsValidCountry returns true if c is a recognized ISO 3166-1 alpha-2 code
// in the master list.  Used by the settings form validator.
func IsValidCountry(c string) bool {
	_, ok := Countries[c]
	return ok
}

// CountryName returns "EN (JP)" for display; falls back to the raw code if
// not in the master list (= unknown but not-blocked).
func CountryName(code string) string {
	if c, ok := Countries[code]; ok {
		return c.NameEN + " (" + c.NameJP + ")"
	}
	return code
}

// CountriesSorted returns the master list sorted by ISO code.  Used to render
// the autocomplete <datalist> in a stable order.
func CountriesSorted() []Country {
	out := make([]Country, 0, len(Countries))
	for _, c := range Countries {
		out = append(out, c)
	}
	// insertion sort by Code (= small N, stable, no extra import)
	for i := 1; i < len(out); i++ {
		j := i
		for j > 0 && out[j-1].Code > out[j].Code {
			out[j-1], out[j] = out[j], out[j-1]
			j--
		}
	}
	return out
}
