package repocheck

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"runtime"
	"strings"
	"testing"

	"github.com/unmask-sh/unmask/admin/internal/settings"
)

// configInitTemplate lifts the YAML that `unmask config-init` writes out of the
// cmd/unmask source.  It lives in package main and cannot be imported, and
// copying it into the test would defeat the point -- the copy is exactly what
// drifts.
func configInitTemplate(t *testing.T) string {
	t.Helper()
	_, self, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	path := filepath.Join(filepath.Dir(self), "..", "..", "cmd", "unmask", "main.go")
	src, err := os.ReadFile(path)
	if err != nil {
		t.Skipf("cmd/unmask/main.go not readable (%v)", err)
	}
	s := string(src)
	i := strings.Index(s, "# unmask config (generated by unmask config-init)")
	if i < 0 {
		t.Fatal("config-init template not found in cmd/unmask/main.go")
	}
	start := strings.LastIndex(s[:i], "`")
	end := strings.Index(s[i:], "`")
	if start < 0 || end < 0 {
		t.Fatal("config-init template is not a raw string literal any more")
	}
	// The two %q are the generated secrets; any valid quoted string will do.
	return regexp.MustCompile(`%q`).ReplaceAllString(s[start+1:i+end], `"deadbeef"`)
}

func loadYAML(t *testing.T, body string) settings.Settings {
	t.Helper()
	p := filepath.Join(t.TempDir(), "config.yml")
	if err := os.WriteFile(p, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	s, err := settings.Load(p)
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	return s
}

// TestConfigInitGlobalMatchesDefaults: config-init runs only when no config
// exists, so its output is what a fresh install gets while an upgrade keeps its
// own file and lands on defaults().  When the two disagree, the same version of
// unmask enforces differently depending on how the host arrived at it, and
// nothing in the build notices -- the stale-browser tier shipped enabled for
// fresh installs and disabled for upgrades for exactly that reason.
//
// If a divergence is ever genuinely wanted, this test is the place to say so
// out loud rather than let it appear by accident.
func TestConfigInitGlobalMatchesDefaults(t *testing.T) {
	fresh := loadYAML(t, configInitTemplate(t)).Global
	upgrade := loadYAML(t, "secret:\n  bv_secret: deadbeef\n").Global

	if reflect.DeepEqual(fresh, upgrade) {
		return
	}
	fv, uv := reflect.ValueOf(fresh), reflect.ValueOf(upgrade)
	for i := 0; i < fv.NumField(); i++ {
		a, b := fv.Field(i), uv.Field(i)
		if !a.CanInterface() || reflect.DeepEqual(a.Interface(), b.Interface()) {
			continue
		}
		t.Errorf("global.%s differs: fresh install %v, upgrade %v — a fresh install "+
			"would enforce differently from an upgraded one",
			fv.Type().Field(i).Name, fmt.Sprint(a.Interface()), fmt.Sprint(b.Interface()))
	}
}
