#!/bin/sh
# unmask docker entrypoint.
#
# Responsibilities:
#   1. If /etc/unmask/admin.yml is missing, generate a minimal skeleton (= the
#      install wizard then captures driver / DB connection info / admin user).
#   2. Pass-through CMD to unmask.
#
# Skeleton values:
#   - db.driver: sqlite, sqlite_path: /var/lib/unmask/unmask.sqlite
#   - secret.bv_secret / captcha_secret_base: random 32B on each startup (= if a
#     yml already exists it is never touched; generated only on the first run).
#   - server.bind: 0.0.0.0,  port: 9477,  base_path: /unmask
#   - nginx.upstream_addr: $UNMASK_DAEMON_ADDR (default 127.0.0.1:9477) = what
#     the rendered nginx config proxies /unmask/ to; compose sets admin:9477
#   - nginx_log.socket_path: /run/unmask/log.sock (share /run/unmask with nginx)
#   3. Before `serve`: migrate the schema and render the nginx includes, the
#      two steps a host install gets from postinstall / the wizard.
set -e

CFG=/etc/unmask/admin.yml

if [ ! -f "$CFG" ]; then
    BV=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
    CB=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
    cat > "$CFG" <<EOF
# unmask admin config (auto-generated by docker entrypoint).
# Use the install wizard to enter the driver / DB connection / admin user.

db:
    driver: sqlite
    sqlite_path: /var/lib/unmask/unmask.sqlite

secret:
    bv_secret: ${BV}
    captcha_secret_base: ${CB}

challenge:
    # Challenge knobs live under default: (multi-site v2 shape); fields placed
    # directly under challenge: are not read by the loader.
    default:
        pow_cookie_valid_seconds: 604800       # 7 days
        captcha_cookie_valid_seconds: 1209600  # 14 days
        captcha:
            provider: builtin
            builtin_score_threshold: 0.5

server:
    bind: 0.0.0.0
    port: 9477
    base_path: /unmask

nginx_log:
    # nginx ships its access log over this unix socket (shared /run/unmask
    # volume) so the dashboard can see cookie-passed traffic.
    socket_path: /run/unmask/log.sock
nginx:
    output_dir: /etc/unmask
    # Where the rendered nginx config proxies /unmask/ to.  A sidecar nginx
    # container reaches this one by service name (compose: admin:9477); a
    # host nginx talking to a published port keeps the loopback default.
    upstream_addr: ${UNMASK_DAEMON_ADDR:-127.0.0.1:9477}
    metrics_allow_from:
        - 127.0.0.1
EOF
    # The file embeds bv_secret + captcha_secret_base, and host bind-mounts
    # (= docker-compose.example.yml: unmask-config:/etc/unmask) surface this
    # file on the host fs -- without this chmod the default umask leaves it
    # world-readable there.
    chmod 0600 "$CFG"
    echo "==> generated minimal $CFG (= visit /unmask/admin/ to start install wizard)"

    # Setup-token: the wizard's anti-hijack gate fails CLOSED, and a container
    # has no postinstall to mint a token, so without one every wizard POST is
    # silently rejected -- a no-feedback dead-end.  Mint one alongside the fresh
    # config and surface it in the logs (read it via `docker logs`, enter it in
    # the wizard).  SetupNeeded clears the token automatically once an admin user
    # exists, so a recreate against a persisted DB never re-locks the UI.
    token=$(head -c 18 /dev/urandom | od -An -tx1 | tr -d ' \n')
    ( umask 077; printf '%s\n' "$token" > /etc/unmask/.setup-token )
    echo "==> unmask setup token (enter this in the wizard): $token"
fi

# Volumes are populated by whichever container mounts them first, and the
# nginx sidecar may win that race and leave them root-owned; the skeleton
# above is also written by root.  The binary drops to `unmask` right after
# start, so everything it will touch has to belong to that user before then.
# Skipped when not root (someone ran the image with --user).
if [ "$(id -u)" = "0" ]; then
    for d in /etc/unmask /var/lib/unmask /run/unmask; do
        [ -d "$d" ] && chown -R unmask:unmask "$d"
    done
fi

# `serve` does not migrate or render on its own (on a host those are
# postinstall / wizard steps).  A container has neither, so do both here:
# the schema must exist before the wizard, and the nginx sidecar refuses to
# start until the includes it references exist in the shared volume.
if [ "${1:-}" = "serve" ]; then
    /usr/local/bin/unmask migrate      -config "$CFG"
    /usr/local/bin/unmask render-nginx -config "$CFG"
fi
exec /usr/local/bin/unmask "$@"
