#!/bin/sh
# unmask docker entrypoint.
#
# Responsibilities:
#   1. If /etc/unmask/admin.yml is missing, generate a minimal skeleton (= the
#      install wizard then captures driver / DB connection info / admin user).
#   2. Pass-through CMD to unmask.
#
# Skeleton values:
#   - db.driver: sqlite, sqlite_path: /var/lib/unmask/unmask.sqlite
#   - secret.bv_secret / captcha_secret_base: random 32B on each startup (= if a
#     yml already exists it is never touched; generated only on the first run).
#   - server.bind: 0.0.0.0,  port: 9477,  base_path: /unmask
#   - nginx.upstream_addr: $UNMASK_DAEMON_ADDR (default 127.0.0.1:9477) = what
#     the rendered nginx config proxies /unmask/ to; compose sets admin:9477
#   - nginx_log.socket_path: /run/unmask/log.sock (share /run/unmask with nginx)
#   3. Before `serve`: migrate the schema and render the nginx includes, the
#      two steps a host install gets from postinstall / the wizard.
set -e

CFG=/etc/unmask/admin.yml

if [ ! -f "$CFG" ]; then
    BV=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
    CB=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
    # A gateway install (settings > Gateway seeded below) redirects :80 to
    # https by default; the redirect lives in server.inc and exempts health
    # checks and ACME.  A module-only container leaves it to the operator's
    # own vhost, as on a host install.
    GATEWAY_REDIRECT_LINE=""
    # UNMASK_TRUSTED_PROXIES on this container seeds a custom row of
    # settings > Network's trusted LB / CDN list (the set the gateway takes
    # the visitor's address from, and the JA4 header is trusted from); the
    # presets there (GCP, Cloudflare, ...) are the usual answer.
    TRUSTED_LB_LINES=""
    if [ -n "${UNMASK_TRUSTED_PROXIES:-}" ]; then
        cidrs=""
        for cidr in ${UNMASK_TRUSTED_PROXIES}; do
            case "$cidr" in *[!0-9a-fA-F:./]*) continue ;; esac
            cidrs="${cidrs}${cidrs:+, }\"${cidr}\""
        done
        [ -n "$cidrs" ] && TRUSTED_LB_LINES="    trusted_lb_extra:
        - id: env_trusted_proxies
          label: UNMASK_TRUSTED_PROXIES
          cidrs: [${cidrs}]"
    fi
    case "${UNMASK_GATEWAY:-}" in 1|true|yes|on) UNMASK_GATEWAY=1 ;; *) UNMASK_GATEWAY="" ;; esac
    if [ -n "${UNMASK_GATEWAY}${UNMASK_UPSTREAM:-}${UNMASK_SERVER_NAME:-}${UNMASK_ACME_EMAIL:-}${UNMASK_TLS_CERT:-}${UNMASK_TLS_MODE:-}" ]; then
        GATEWAY_REDIRECT_LINE="    https_redirect: true"
    fi
    cat > "$CFG" <<EOF
# unmask admin config (auto-generated by docker entrypoint).
# Use the install wizard to enter the driver / DB connection / admin user.

db:
    driver: sqlite
    sqlite_path: /var/lib/unmask/unmask.sqlite

secret:
    bv_secret: ${BV}
    captcha_secret_base: ${CB}

challenge:
    # Challenge knobs live under default: (multi-site v2 shape); fields placed
    # directly under challenge: are not read by the loader.
    default:
        pow_cookie_valid_seconds: 604800       # 7 days
        captcha_cookie_valid_seconds: 1209600  # 14 days
        captcha:
            provider: builtin
            builtin_score_threshold: 0.5

server:
    bind: 0.0.0.0
    port: 9477
    base_path: /unmask

nginx_log:
    # nginx ships its access log over this unix socket (shared /run/unmask
    # volume) so the dashboard can see cookie-passed traffic.
    socket_path: /run/unmask/log.sock
nginx:
    output_dir: /etc/unmask
${GATEWAY_REDIRECT_LINE}
    # Where the rendered nginx config proxies /unmask/ to.  A sidecar nginx
    # container reaches this one by service name (compose: admin:9477); a
    # host nginx talking to a published port keeps the loopback default.
    upstream_addr: ${UNMASK_DAEMON_ADDR:-127.0.0.1:9477}
    metrics_allow_from:
        - 127.0.0.1
${TRUSTED_LB_LINES}
EOF
    # The file embeds bv_secret + captcha_secret_base, and host bind-mounts
    # (= docker-compose.example.yml: unmask-config:/etc/unmask) surface this
    # file on the host fs -- without this chmod the default umask leaves it
    # world-readable there.
    # Container gateway (UNMASK_GATEWAY=1, or any of the older variables):
    # seed settings > Gateway from the environment the compose file hands
    # this container, so the first render already carries the upstream,
    # the hostnames and a certificate source and the gateway can start.
    # With nothing but UNMASK_GATEWAY=1 that is: any hostname, a self-signed
    # certificate the render generates, and the upstream left to the tab
    # (or to the nginx container's UNMASK_UPSTREAM).  Seeded once; from then
    # on the admin UI is the source of truth.
    if [ -n "${UNMASK_GATEWAY}${UNMASK_UPSTREAM:-}${UNMASK_SERVER_NAME:-}${UNMASK_ACME_EMAIL:-}${UNMASK_TLS_CERT:-}${UNMASK_TLS_MODE:-}" ]; then
        mode=selfsigned
        # Files when named, or when the default mount is there to be read.
        if [ -n "${UNMASK_TLS_CERT:-}${UNMASK_TLS_KEY:-}" ] || [ -f /etc/unmask/tls/fullchain.pem ]; then mode=files; fi
        [ -n "${UNMASK_ACME_EMAIL:-}" ] && mode=acme
        # UNMASK_TLS_MODE overrides: none (TLS terminated by a load balancer
        # in front, :80 only), files, acme, upload, selfsigned.
        case "${UNMASK_TLS_MODE:-}" in none|files|acme|upload|selfsigned) mode="$UNMASK_TLS_MODE" ;; esac
        listen='[http, https]'; vhmode="$mode"
        if [ "$mode" = none ]; then listen='[http]'; vhmode=selfsigned; fi
        # "_" (or nothing) = any hostname; otherwise the list, which is
        # also what the seeded certificate is for.
        hostmode=all; hostnames='""'
        case "${UNMASK_SERVER_NAME:-_}" in _|"") ;; *) hostmode=custom; hostnames="${UNMASK_SERVER_NAME}" ;; esac
        insecure=false
        case "${UNMASK_ACME_INSECURE:-}" in 1|true|yes|on) insecure=true ;; esac
        cat >> "$CFG" <<EOF
gateway:
    listen: ${listen}
    upstream: ${UNMASK_UPSTREAM:-}
    hostnames:
        mode: ${hostmode}
        names: ${hostnames}
    acme_email: ${UNMASK_ACME_EMAIL:-}
    acme_directory: ${UNMASK_ACME_DIRECTORY:-}
    acme_insecure: ${insecure}
    certificates:
        - mode: ${vhmode}
          domains: ${hostnames}
EOF
        if [ "$vhmode" = files ]; then
            cat >> "$CFG" <<EOF
          cert_path: ${UNMASK_TLS_CERT:-/etc/unmask/tls/fullchain.pem}
          key_path: ${UNMASK_TLS_KEY:-/etc/unmask/tls/privkey.pem}
EOF
        fi
    fi
    chmod 0600 "$CFG"
    echo "==> generated minimal $CFG (= visit /unmask/admin/ to start install wizard)"

    # Setup-token: the wizard's anti-hijack gate fails CLOSED, and a container
    # has no postinstall to mint a token, so without one every wizard POST is
    # silently rejected -- a no-feedback dead-end.  Mint one alongside the fresh
    # config and surface it in the logs (read it via `docker logs`, enter it in
    # the wizard).  SetupNeeded clears the token automatically once an admin user
    # exists, so a recreate against a persisted DB never re-locks the UI.
    token=$(head -c 18 /dev/urandom | od -An -tx1 | tr -d ' \n')
    ( umask 077; printf '%s\n' "$token" > /var/lib/unmask/.setup-token )
    echo "==> unmask setup token (enter this in the wizard): $token"
fi

# Volumes are populated by whichever container mounts them first, and the
# nginx sidecar may win that race and leave them root-owned; the skeleton
# above is also written by root.  The binary drops to `unmask` right after
# start, so everything it will touch has to belong to that user before then.
# Skipped when not root (someone ran the image with --user).
if [ "$(id -u)" = "0" ]; then
    for d in /etc/unmask /var/lib/unmask /run/unmask; do
        # A read-only bind mount inside the volume (certificates mounted for
        # the Gateway tab, e.g. ./tls) cannot be chowned and need not be:
        # the daemon only reads them.  Keep going; a volume that really is
        # not writable fails loudly at migrate/render right after.
        [ -d "$d" ] && { chown -R unmask:unmask "$d" 2>/dev/null || echo "entrypoint: chown $d: read-only entries left as they are" >&2; }
    done
fi

# `serve` does not migrate or render on its own (on a host those are
# postinstall / wizard steps).  A container has neither, so do both here:
# the schema must exist before the wizard, and the nginx sidecar refuses to
# start until the includes it references exist in the shared volume.
if [ "${1:-}" = "serve" ]; then
    /usr/local/bin/unmask migrate      -config "$CFG"
    /usr/local/bin/unmask render-nginx -config "$CFG"
fi
exec /usr/local/bin/unmask "$@"
