#!/bin/sh
# unmask docker entrypoint.
#
# Responsibilities:
#   1. If /etc/unmask/admin.yml is missing, generate a minimal skeleton (= the
#      install wizard then captures driver / DB connection info / admin user).
#   2. Pass-through CMD to unmask.
#
# Skeleton values:
#   - db.driver: sqlite, sqlite_path: /var/lib/unmask/unmask.sqlite
#   - secret.bv_secret / captcha_secret_base: random 32B on each startup (= if a
#     yml already exists it is never touched; generated only on the first run).
#   - server.bind: 0.0.0.0,  port: 9477,  base_path: /unmask
set -e

CFG=/etc/unmask/admin.yml

if [ ! -f "$CFG" ]; then
    BV=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
    CB=$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')
    cat > "$CFG" <<EOF
# unmask admin config (auto-generated by docker entrypoint).
# Use the install wizard to enter the driver / DB connection / admin user.

db:
    driver: sqlite
    sqlite_path: /var/lib/unmask/unmask.sqlite

secret:
    bv_secret: ${BV}
    captcha_secret_base: ${CB}

challenge:
    pow_cookie_valid_seconds: 604800       # 7 days
    captcha_cookie_valid_seconds: 1209600  # 14 days
    captcha_score_threshold: 0.5

server:
    bind: 0.0.0.0
    port: 9477
    base_path: /unmask

nginx:
    output_dir: /etc/unmask
    upstream_addr: 127.0.0.1:9477
    admin_allow_from:
        - 127.0.0.1
        - ::1
    metrics_allow_from:
        - 127.0.0.1
EOF
    # The file embeds bv_secret + captcha_secret_base, and host bind-mounts
    # (= docker-compose.example.yml: unmask-config:/etc/unmask) surface this
    # file on the host fs -- without this chmod the default umask leaves it
    # world-readable there.
    chmod 0600 "$CFG"
    echo "==> generated minimal $CFG (= visit /unmask/admin/ to start install wizard)"
fi

exec /usr/local/bin/unmask "$@"
