#!/bin/sh
# unmask-release postinstall (deb).
#
# Distribution uses a single path / single suite:
#   https://unmask.sh/dl/deb/dists/stable/main/binary-{amd64,arm64}/...
# Per-distro / per-codename paths have been retired (= unified on 2026-05-10).  Debian /
# Ubuntu / Raspbian / Mint / Pop / Devuan etc. all run on the same .deb binaries.


mkdir -p /etc/apt/sources.list.d /etc/apt/keyrings
SOURCES_FILE=/etc/apt/sources.list.d/unmask.sources

cat > "$SOURCES_FILE" <<EOF
# Generated by unmask-release postinstall on $(date -u +%Y-%m-%dT%H:%M:%SZ).
Types: deb
URIs: https://unmask.sh/dl/deb
Suites: stable
Components: main
Architectures: amd64 arm64
Signed-By: /etc/apt/keyrings/unmask.gpg
EOF

exit 0
