#!/bin/sh
# unmask-release postinstall (rpm).
#
# Distribution uses a single path:
#   https://unmask.sh/dl/rpm/$basearch/{RPMS,repodata}/
# Per-distro / per-major dirs were retired (= unified on 2026-05-10).  The Go
# static binary is glibc-independent, so the same binary runs on EL6/7/8/9/10 +
# Fedora + opensuse, etc.  zypper-family distros place repo files in a different
# directory, so a single case branch handles that.


# /etc/os-release is standard from systemd-era distros onward (= RHEL 7+ / Debian 8+).
# EOL distros like CentOS 6 lack it, so fall back to the yum-family assumption
# (= the majority) when absent.
if [ -f /etc/os-release ]; then
    . /etc/os-release
fi

# zypper-family (= openSUSE / SLES) uses /etc/zypp/repos.d/, others (yum/dnf)
# use /etc/yum.repos.d/.
case "${ID:-}${ID_LIKE:-}" in
    *suse*) REPO_DIR=/etc/zypp/repos.d ;;
    *)      REPO_DIR=/etc/yum.repos.d ;;
esac
mkdir -p "$REPO_DIR"
REPO_FILE="$REPO_DIR/unmask.repo"

cat > "$REPO_FILE" <<EOF
# Generated by unmask-release postinstall on $(date -u +%Y-%m-%dT%H:%M:%SZ).
[unmask]
name=unmask repository
baseurl=https://unmask.sh/dl/rpm/\$basearch
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-unmask
metadata_expire=300
EOF

exit 0
