#!/bin/sh
# unmask-release postinstall (deb).
#
# Distribution uses a single path / single suite:
#   https://unmask.sh/dl/deb/dists/stable/main/binary-{amd64,arm64}/...
# Per-distro / per-codename paths have been retired (= unified on 2026-05-10).  Debian /
# Ubuntu / Raspbian / Mint / Pop / Devuan etc. all run on the same .deb binaries.


mkdir -p /etc/apt/sources.list.d /etc/apt/keyrings
SOURCES_FILE=/etc/apt/sources.list.d/unmask.sources

cat > "$SOURCES_FILE" <<EOF
# Generated by unmask-release postinstall on $(date -u +%Y-%m-%dT%H:%M:%SZ).
Types: deb
URIs: https://unmask.sh/dl/deb
Suites: stable
Components: main
Architectures: amd64 arm64
Signed-By: /etc/apt/keyrings/unmask.gpg
EOF

# Pre-release channel, deliberately not reachable by an ordinary upgrade.  It
# is here so that confirming a fix takes one command and no setup:
#
#   sudo apt update
#   sudo apt install unmask=<version>          # the build being confirmed
#
# apt has no per-command --enablerepo, so the equivalent is a pin: the suite is
# available but its priority is below the "never install from here unless asked
# by name" line, so `apt upgrade` cannot wander into a pre-release and there is
# no state to undo afterwards.
#
# Same keyring as stable.  Whoever reported a bug should not have to import a
# second key to help.
cat > "${SOURCES_FILE%.sources}-testing.sources" <<EOF
# Generated by unmask-release postinstall on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Pre-release builds.  Pinned below the "only on request" line -- see
# /etc/apt/preferences.d/unmask-testing.pref.
Types: deb
URIs: https://unmask.sh/dl/testing/deb
Suites: testing
Components: main
Architectures: amd64 arm64
Signed-By: /etc/apt/keyrings/unmask.gpg
EOF

mkdir -p /etc/apt/preferences.d
cat > /etc/apt/preferences.d/unmask-testing.pref <<EOF
# Generated by unmask-release postinstall.
# Priority 100 is below the installed-package threshold, so apt never upgrades
# INTO this suite on its own; it is only used when a version from it is asked
# for by name.
#
# Pinned on BOTH origin and suite, and that pair matters twice over:
#   - "origin unmask.sh" alone would demote the STABLE repo too, since both
#     suites are served from the same host -- ordinary upgrades would stop.
#   - "a=testing" alone would match Debian's own testing suite on any machine
#     that has it configured, and demote that instead.
# o=unmask comes from APT::FTPArchive::Release::Origin in build-repo.sh.
Package: *
Pin: release o=unmask,a=testing
Pin-Priority: 100
EOF

exit 0
