#!/bin/sh
# unmask-web-nginx postinstall.
#
# Role:
#   1. Place upstream auto-load symlinks in /etc/nginx/conf.d/
#       00-unmask-upstream.conf -> /etc/unmask/upstream.conf
#         (= so proxy_pass http://unmask_admin; resolves in every server block. shared by both modes)
#       00-unmask.conf          -> /etc/unmask/native/http.inc
#         (= JA4 maps / log_format etc.  native-mode only.  In environments
#            without the plugin, the target is not rendered but nginx -t still
#            passes; include only emits a warning.)
#   2. Validate syntax with nginx -t and attempt reload
#   3. Print the setup wizard URL + token

echo "unmask-web-nginx: installing nginx integration..."

# upstream auto-load (= shared by both modes).  /etc/unmask/upstream.conf is
# generated by the unmask main package postinstall, or by the admin daemon's
# initial render.
# nginx's wildcard include hits emerg on a broken symlink (= missing target),
# so touch an empty target right after install — there is a window before the
# admin daemon has done its first render.
# (The admin daemon will later overwrite this with the correct contents.)
UPSTREAM_SRC=/etc/unmask/upstream.conf
UPSTREAM_LINK=/etc/nginx/conf.d/00-unmask-upstream.conf
[ -d /etc/unmask ] || mkdir -p /etc/unmask
[ -e "$UPSTREAM_SRC" ] || : > "$UPSTREAM_SRC"
# Alpine ships only /etc/nginx/http.d/ by default, but the stock nginx.conf
# still includes /etc/nginx/conf.d/*.conf -- creating the dir lets our
# symlinks land in conf.d/ on every distro without forking the path.
mkdir -p /etc/nginx/conf.d
if [ ! -L "$UPSTREAM_LINK" ] && [ ! -e "$UPSTREAM_LINK" ]; then
    ln -sf "$UPSTREAM_SRC" "$UPSTREAM_LINK"
    echo "unmask-web-nginx: symlinked $UPSTREAM_LINK -> $UPSTREAM_SRC"
fi

# JA4 maps auto-load (= native-mode only).  Meaningful only with the
# unmask-plugin-nginx + admin combination.  Even without the plugin, keep the
# symlink alive by pointing it at an empty placeholder that is still rendered.
RENDERED_SRC=/etc/unmask/native/http.inc
RENDERED_LINK=/etc/nginx/conf.d/00-unmask.conf
[ -d /etc/unmask/native ] || mkdir -p /etc/unmask/native
[ -e "$RENDERED_SRC" ] || : > "$RENDERED_SRC"
# cleanup of the legacy symlink
rm -f /etc/nginx/conf.d/00-unmask-rendered.conf
if [ ! -L "$RENDERED_LINK" ] && [ ! -e "$RENDERED_LINK" ]; then
    ln -sf "$RENDERED_SRC" "$RENDERED_LINK"
    echo "unmask-web-nginx: symlinked $RENDERED_LINK -> $RENDERED_SRC"
fi

# SELinux: nginx defaults to the httpd_t domain on RHEL-family distros, where
# auth_request / proxy_pass to 127.0.0.1:9477 is kernel-blocked unless the
# httpd_can_network_connect bool is on.  Without this the bot challenge never
# fires -- the visitor lands on the backend as if unmask were absent.  Auto-
# enable so install-and-go works; opt out by setting UNMASK_SKIP_SETSEBOOL=1
# before install.  Bool is persistent (-P) so it survives reboots.
if [ -z "${UNMASK_SKIP_SETSEBOOL:-}" ] \
   && command -v getenforce >/dev/null 2>&1 \
   && [ "$(getenforce 2>/dev/null)" = "Enforcing" ] \
   && command -v setsebool >/dev/null 2>&1 \
   && command -v getsebool >/dev/null 2>&1; then
    if getsebool httpd_can_network_connect 2>/dev/null | grep -q ' --> off'; then
        if setsebool -P httpd_can_network_connect 1 2>/dev/null; then
            echo "unmask-web-nginx: SELinux setsebool -P httpd_can_network_connect 1 applied"
            echo "  (= nginx can now proxy_pass to unmask-admin.  set UNMASK_SKIP_SETSEBOOL=1 to opt out)"
        else
            echo "unmask-web-nginx: WARNING -- setsebool failed."
            echo "  -> run manually: sudo setsebool -P httpd_can_network_connect 1"
        fi
    fi
fi

if command -v nginx >/dev/null 2>&1; then
    if nginx -t >/dev/null 2>&1; then
        nginx -s reload >/dev/null 2>&1 || true
        echo "unmask-web-nginx: nginx reload requested."
    else
        echo "unmask-web-nginx: WARNING — 'nginx -t' did NOT pass."
        echo "  → check the conflict (often duplicate 'upstream' or 'server' definitions)."
        echo "  → run 'sudo nginx -t' to see the error, fix, then 'sudo nginx -s reload'."
    fi
else
    echo "unmask-web-nginx: nginx binary not found — install nginx first, then 'nginx -s reload'."
fi

# setup wizard URL + token hint (= the main package creates .setup-token on first install).
TOKEN_FILE=/etc/unmask/.setup-token
host=$(hostname -f 2>/dev/null || hostname 2>/dev/null || echo localhost)
echo ""
echo "================================================================"
echo "  unmask — initial setup"
echo "  ================================================================"
echo "  Setup wizard URL:  /unmask/admin/setup/"
if [ -r "$TOKEN_FILE" ]; then
    token=$(cat "$TOKEN_FILE" 2>/dev/null || true)
    if [ -n "$token" ]; then
        echo "  Setup token:       $token"
        echo "  (re-display:        sudo cat $TOKEN_FILE)"
    fi
fi
echo ""
echo "  How to reach the setup wizard:"
echo ""
echo "  [1] Recommended — add 1 line to your existing nginx vhost"
echo "        Edit a server { } block in /etc/nginx/conf.d/ and add:"
echo ""
echo "            include /etc/unmask/auth_request/server.inc;"
echo ""
echo "        (native mode with unmask-plugin-nginx: use /etc/unmask/native/server.inc)"
echo "        then:  sudo nginx -t && sudo nginx -s reload"
echo "        open:  https://<your-domain>/unmask/admin/setup/"
echo ""
echo "  [2] Direct port (= dev / lab, or private network)"
echo "        Edit /etc/unmask/config.yml → server.bind: 0.0.0.0:9477"
echo "        sudo systemctl restart unmask-admin"
echo "        open:  http://${host}:9477/unmask/admin/setup/"
echo ""
echo "  [3] SSH tunnel (= universal fallback, no nginx setup needed)"
echo "        \$ ssh -L 9477:127.0.0.1:9477 ${host} -N &"
echo "        open:  http://localhost:9477/unmask/admin/setup/"
echo ""
echo "  After setup, add protection to your location { } block:"
echo "        include /etc/unmask/auth_request/protect.inc;  # fires the bot challenge"
echo ""
if [ ! -r "$TOKEN_FILE" ]; then
    echo "     The setup token is at /etc/unmask/.setup-token (= view with sudo cat)."
fi
echo "================================================================"
echo ""

exit 0
