#!/bin/sh
# 初回 install / upgrade 後に走る.
#   - /etc/unmask/config.yml が無ければ unmask-admin config-init で生成
#   - schema 適用 (idempotent)
#   - systemd reload + enable
set -eu

CONFIG=/etc/unmask/config.yml
NGINX_SECRET=/etc/unmask/nginx/secret.conf

if [ ! -f "$CONFIG" ]; then
    /usr/sbin/unmask-admin config-init -out "$CONFIG"
    chown root:unmask "$CONFIG"
    chmod 0640 "$CONFIG"
    echo "unmask: generated $CONFIG with random secrets"
fi

# nginx 側の secret.conf を config.yml の bv_secret から同期生成.
# nginx user が読めるよう 0644 (BV_SECRET の機密性は middle. 漏洩した場合は
# config.yml の secret.bv_secret も同時に rotate すること).
if [ ! -f "$NGINX_SECRET" ]; then
    BV=$(awk -F'"' '/^[[:space:]]*bv_secret:/ { print $2; exit }' "$CONFIG")
    DAYS=$(awk '/^[[:space:]]*cookie_days:/ { print $2; exit }' "$CONFIG")
    DAYS=${DAYS:-3}
    if [ -n "$BV" ]; then
        cat > "$NGINX_SECRET" <<EOF
# auto-generated by unmask postinstall from $CONFIG
# do not edit by hand. rotate via $CONFIG and re-run \`systemctl reload nginx\`.
unmask_bv_secret      "$BV";
unmask_bv_valid_days  $DAYS;
EOF
        chmod 0644 "$NGINX_SECRET"
        echo "unmask: generated $NGINX_SECRET"
    else
        echo "unmask: WARNING: could not extract bv_secret from $CONFIG; copy secret.conf.example manually"
    fi
fi

# schema (CREATE TABLE IF NOT EXISTS なので既存環境でも安全)
/usr/sbin/unmask-admin migrate -config "$CONFIG" || true

if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload || true
    # 自動起動はオプトイン. 初回 install 時に enable, upgrade 時は据え置き.
    if [ "${1:-}" = "1" ] || [ "${1:-}" = "configure" ]; then
        systemctl enable --now unmask-admin.service || true
        systemctl enable --now unmask-aggregate.timer || true
    else
        systemctl try-restart unmask-admin.service || true
    fi
fi

echo "unmask: install complete."
echo "  next steps:"
echo "    1. add 'load_module /usr/lib/nginx/modules/ngx_http_ja4_module.so;' to nginx.conf"
echo "    2. add 'include /etc/unmask/nginx/unmask.conf;' inside the http {} block"
echo "    3. add 'include /etc/unmask/nginx/unmask-server.conf;' inside protected server {} blocks"
echo "    4. nginx -t && systemctl reload nginx"
