// Install wizard (= the first-run flow modeled after Cacti / Zabbix / Nextcloud).
//
// Right after start: any `/admin/*` access -> redirect to `/admin/setup/`
// if setup is needed.  After setup completes, hitting `/admin/setup/*`
// redirects to `/admin/` (= prevent re-setup).
//
// Steps:
//  1. welcome
//  2. choose DB driver (sqlite / mariadb) + connection test + save admin.yml + migration
//  3. create administrator account (= the first row in unmask_user)
//  4. done -> on to login
//
// setupNeeded() returns true when any of:
//   - h.DB == nil                (= initial start failed to connect)
//   - unmask_user table missing  (= migration not run)
//   - 0 users in the DB          (= no admin yet)
package handlers

import (
	"context"
	"crypto/subtle"
	"errors"
	"fmt"
	"io/fs"
	"log"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"time"

	"github.com/unmask-sh/unmask/admin/internal/db"
	"github.com/unmask-sh/unmask/admin/internal/i18n"
	"github.com/unmask-sh/unmask/admin/internal/nginxconf"
	"github.com/unmask-sh/unmask/admin/internal/settings"
	"github.com/unmask-sh/unmask/admin/internal/user"
)

// setupMu: serializes DB swap / settings save.
var setupMu sync.Mutex

// SetupNeeded: decide whether to send the user to the setup wizard.
//
// step:
//   "db"   : DB not connected OR table missing -> step 2 (DB picker)
//   "user" : DB OK but 0 rows in unmask_user   -> step 3 (create admin user)
//   ""     : setup not needed
//
// step != "" means "setup is needed" -> route to the wizard.

// SetupTokenPath: path to a token file used to prevent a third party from
// completing setup ahead of the admin.  Generated by the rpm/deb/apk
// postinstall as 0600 unmask:unmask, so only someone who can
// `sudo cat` it (= a sudoer on the host) can finish setup.  The file is
// deleted on completion so the wizard can't be re-run.
//
// The token is transient state, not configuration, so it lives under
// /var/lib/unmask (FHS), not next to config.yml in /etc.
//
// It is a var, not a const: `unmask serve` overrides it (SetSetupTokenDir)
// for a relocated install (-config /opt/unmask/config.yml, or a second
// instance), which reads its OWN token instead of the shared default.
var SetupTokenPath = "/var/lib/unmask/.setup-token"

// legacySetupTokenPath: where releases up to 0.1.8 (and their postinstalls)
// put the token.  Read/removed as a fallback so an install that upgraded
// mid-setup — token minted at the old path, wizard not yet completed — can
// still finish the wizard.  Cleared by SetSetupTokenDir for relocated
// installs, which never used the /etc default.
var legacySetupTokenPath = "/etc/unmask/.setup-token"

const SetupTokenCookieName = "unmask_setup_token"

// SetSetupTokenDir points the setup-token file at dir/.setup-token.  Called by
// `unmask serve` with the directory of the resolved config file.  Empty dir or
// the standard /etc/unmask is ignored (keeps the /var/lib default), so both a
// no-config dev run and a package install land on the same sane path.
func SetSetupTokenDir(dir string) {
	if dir != "" && filepath.Clean(dir) != "/etc/unmask" {
		SetupTokenPath = filepath.Join(dir, ".setup-token")
		legacySetupTokenPath = ""
	}
}

// readSetupToken: read the token from the file.  Empty / unreadable -> "";
// falls back to the pre-0.1.9 location so an upgrade mid-setup keeps working.
func readSetupToken() string {
	for _, p := range []string{SetupTokenPath, legacySetupTokenPath} {
		if p == "" {
			continue
		}
		if b, err := os.ReadFile(p); err == nil {
			return strings.TrimSpace(string(b))
		}
	}
	return ""
}

// hasValidSetupToken: does the current request carry a valid token cookie?
// Production rpm/deb/apk installs generate the token via postinstall; Docker
// containers and local dev opt in to wizard-open mode by setting the
// UNMASK_OPEN_SETUP=1 env var explicitly.  Empty / unreadable token files
// (= partial write, truncation) used to fail open, which let the first
// caller of /admin/setup/ on a fresh internet-reachable instance become
// superadmin.  Fail closed instead.
func hasValidSetupToken(r *http.Request) bool {
	expected := readSetupToken()
	if expected == "" {
		// Explicit opt-in for dev/docker shells where there is no
		// postinstall to write a token.  Anyone deploying with this on must
		// make /admin/setup/ unreachable from the public internet themselves.
		return os.Getenv("UNMASK_OPEN_SETUP") == "1"
	}
	c, err := r.Cookie(SetupTokenCookieName)
	if err != nil {
		return false
	}
	return subtle.ConstantTimeCompare([]byte(c.Value), []byte(expected)) == 1
}

// removeSetupToken: delete the token file on setup completion so the
// wizard can no longer be triggered.  Removes the legacy-path file too so
// a token minted by a pre-0.1.9 postinstall can't linger after completion.
func removeSetupToken() {
	for _, p := range []string{SetupTokenPath, legacySetupTokenPath} {
		if p == "" {
			continue
		}
		if err := os.Remove(p); err != nil && !os.IsNotExist(err) {
			log.Printf("setup token remove: %v", err)
		}
	}
}

func (h *Handler) SetupNeeded(r *http.Request) (needed bool, step string) {
	if h == nil {
		return false, ""
	}
	// Wizard phase = the setup token file is still present.  Step comes
	// from in-flight wizard state (= deferred-commit model).  The token
	// file is removed at the end of AdminSetupInstall.
	if _, err := os.Stat(SetupTokenPath); err == nil {
		// A token file is present but the admin user table is already
		// populated -> the token is stale.  A deb `configure` (and any package
		// that re-runs the postinstall) recreates .setup-token on EVERY
		// upgrade, not just fresh installs; re-entering the wizard here would
		// 302-loop every admin route and let "re-completing" it rewrite the DB
		// block to SQLite (orphaning MariaDB).  Treat setup as done and clean
		// the stale token up.
		if h.DB != nil {
			ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
			var n int
			err := h.DB.QueryRowContext(ctx, `SELECT COUNT(*) FROM unmask_user`).Scan(&n)
			cancel()
			if err == nil && n > 0 {
				removeSetupToken()
				return false, ""
			}
		}
		// Without a verified token cookie, we can't read wizard state — go
		// to the token step.
		if !hasValidSetupToken(r) {
			return true, "token"
		}
		s := h.getWizardState(r)
		if s == nil {
			return true, "token"
		}
		return true, s.step()
	}
	// Post-install fallback: anything that genuinely needs setup attention
	// (= no DB connection, no admin user) routes back to the wizard.  In
	// practice, install removes the token first and these branches don't
	// fire — but they protect against partial state.
	if h.DB == nil {
		return true, "db"
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	var n int
	row := h.DB.QueryRowContext(ctx, `SELECT COUNT(*) FROM unmask_user`)
	if err := row.Scan(&n); err != nil {
		return true, "db"
	}
	if n == 0 {
		return true, "user"
	}
	return false, ""
}

// setupHasAdmin reports whether an admin account already exists (= setup has
// been completed at least once).  A nil DB or a query error is treated as "no
// admin" so a fresh / not-yet-migrated install still reaches the wizard.
func (h *Handler) setupHasAdmin() bool {
	if h.DB == nil {
		return false
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	var n int
	if err := h.DB.QueryRowContext(ctx, `SELECT COUNT(*) FROM unmask_user`).Scan(&n); err != nil {
		return false
	}
	return n > 0
}

// setupSuperadmin returns the session payload IFF the request is an
// authenticated superadmin that also clears the admin IP allowlist.  Once setup
// is complete the bootstrap token is gone, so re-running the wizard is gated by
// the same auth as the rest of the admin (= a logged-in superadmin), not a
// token.  Returns nil otherwise.
func (h *Handler) setupSuperadmin(r *http.Request) *SessionPayload {
	// Same IP allowlist every other admin route enforces.
	ip := adminClientIP(r, h.snapshotSettings())
	if !ipAllowed(ip, settings.EnabledValues(h.cfg().Nginx.AdminAllowedIPs, h.cfg().Nginx.AdminAllowedIPsDisabled)) {
		return nil
	}
	c, err := r.Cookie(sessionCookieName)
	if err != nil {
		return nil
	}
	pay := verifySessionCookie(h.cfg().Secret.BVSecret, c.Value)
	if pay == nil {
		return nil
	}
	// Honor the CURRENT DB role so a demoted account can't reconfigure on a
	// frozen cookie (mirrors AuthMiddleware).
	if h.UserRepo != nil {
		if u, uerr := h.UserRepo.GetByID(r.Context(), pay.UserID); uerr == nil && u != nil {
			pay.Role = u.Role
		}
	}
	if !roleAtLeast(pay.Role, user.RoleSuperadmin) {
		return nil
	}
	return pay
}

// setupCSRFOK guards a setup POST against CSRF.  Reconfigure POSTs are made by
// an authenticated superadmin, so they MUST echo the CSRF token (a malicious
// page could otherwise drive a logged-in superadmin into repointing the DB);
// bootstrap POSTs carry no session and are instead protected by the unguessable
// setup token, so they skip the check.  ParseForm must have run for url-encoded
// bodies.  Writes 403 and returns false on failure.
func (h *Handler) setupCSRFOK(w http.ResponseWriter, r *http.Request) bool {
	if h.setupSuperadmin(r) != nil && !verifyCSRF(r) {
		http.Error(w, "forbidden (csrf)", http.StatusForbidden)
		return false
	}
	return true
}

// wizardStateKey derives the key for the in-flight wizard state.  A logged-in
// superadmin always keys by session (reconfigure) so the deferred-commit flow
// works without a token -- checked FIRST so it still holds when the live DB has
// no admin (e.g. mid-switch to a fresh / empty DB).  Keying off setupHasAdmin()
// first would instead drop the operator into the token branch, which has no
// token on an already-configured install, and lock them out with "re-enter the
// token".  A tokenless bootstrap (no admin, no session) keys by the setup-token
// cookie.  Empty when the request may not hold any state.
func (h *Handler) wizardStateKey(r *http.Request) string {
	if pay := h.setupSuperadmin(r); pay != nil {
		return "sess:" + strconv.FormatInt(pay.UserID, 10)
	}
	if !h.setupHasAdmin() {
		if c, err := r.Cookie(SetupTokenCookieName); err == nil {
			return c.Value
		}
	}
	return ""
}

// getWizardState returns the in-flight wizard state for the request using the
// mode-aware key, or nil when the request isn't authorized to hold any.
func (h *Handler) getWizardState(r *http.Request) *wizardState {
	return wizardStateForKey(h.wizardStateKey(r))
}

// SetupGate guards the setup endpoints and the bootstrap forced-redirect.
//
//   - Bootstrap (no admin yet): setup is mandatory.  Non-setup paths bounce to
//     the wizard; the wizard itself is gated by the setup token inside the
//     handlers.
//   - Configured (admin exists): setup is complete and /setup/ becomes a
//     superadmin-only reconfigure surface.  A non-superadmin (or unauthenticated)
//     request to /setup/ is bounced to /admin/; everything else passes through.
func (h *Handler) SetupGate(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		base := h.cfg().Server.BasePath
		isSetupPath := strings.HasPrefix(r.URL.Path, base+"/admin/setup")

		if !h.setupHasAdmin() {
			// Bootstrap: the token gates the wizard; force everything else to it.
			needed, _ := h.SetupNeeded(r)
			if needed && !isSetupPath {
				http.Redirect(w, r, base+"/admin/setup/", http.StatusFound)
				return
			}
			next(w, r)
			return
		}

		// Configured: /setup/ is reconfigure-only, gated by superadmin auth
		// (token no longer applies).  Other paths are unaffected.
		if isSetupPath && h.setupSuperadmin(r) == nil {
			http.Redirect(w, r, base+"/admin/", http.StatusFound)
			return
		}
		next(w, r)
	}
}

// targetDBStats returns the admin-user and event-record counts of the DB the
// wizard is about to install against, for the reconfigure review summary.  A
// table that doesn't exist yet (= a fresh DB) counts as 0.  The live handle is
// reused when the target matches the current config; otherwise a throwaway
// connection is opened and closed.
func (h *Handler) targetDBStats(dbcfg settings.DB) (users, events int) {
	var conn *db.DB
	if h.DB != nil && dbcfg == h.cfg().DB {
		conn = h.DB
	} else {
		c, err := db.Open(dbcfg)
		if err != nil {
			return 0, 0
		}
		defer c.Close()
		conn = c
	}
	_ = conn.QueryRow(`SELECT COUNT(*) FROM unmask_user`).Scan(&users)
	_ = conn.QueryRow(`SELECT COUNT(*) FROM unmask_event`).Scan(&events)
	return users, events
}

// targetDBHasUsername reports whether username already exists in the target DB,
// so the user step can reject a duplicate immediately instead of letting it fail
// at install.  A missing table / unopenable DB returns false (= install stays
// the backstop).
func (h *Handler) targetDBHasUsername(dbcfg settings.DB, username string) bool {
	var conn *db.DB
	if h.DB != nil && dbcfg == h.cfg().DB {
		conn = h.DB
	} else {
		c, err := db.Open(dbcfg)
		if err != nil {
			return false
		}
		defer c.Close()
		conn = c
	}
	u, err := user.New(conn).GetByUsername(context.Background(), username)
	return err == nil && u != nil
}

// reconfigureNoOp reports whether running install against the wizard's selected
// DB would change nothing: it targets the DB the daemon already runs (so no
// swap, and migrate is idempotent) AND creates no new admin (the target already
// has one that install would adopt).  The review step hides the install button
// for this case and a direct install POST short-circuits back to the dashboard.
func (h *Handler) reconfigureNoOp(s *wizardState) bool {
	if s == nil || s.UserSet || s.DB != h.cfg().DB {
		return false
	}
	u, _ := h.targetDBStats(s.DB)
	return u > 0
}

// AdminSetupIndex: GET {base}/admin/setup/  — render the current step.
//
// step order: token -> db -> user -> done.
// token only fires when the file exists AND the cookie isn't verified
// yet.  When the file is absent (= dev/docker), skip token and go
// straight to the db step.
// existingDBInfo describes a database that already carries this install's
// schema, so the wizard can offer to keep using it by name instead of
// presenting the driver choice as though nothing existed yet.
type existingDBInfo struct {
	Driver   string // display label: "SQLite" / "MariaDB / MySQL"
	Location string // file path, or user@host:port/database
	Events   int64  // rows already recorded, so the operator can recognise it
}

// detectExistingDB reports the configured database when it is reachable AND
// already migrated.  Package installs are always in this state by the time
// anyone opens the wizard: the postinstall writes config.yml, the daemon
// starts, migrates, and begins recording traffic.  Offering only "SQLite or
// MariaDB" at that point reads as "pick one and build it from scratch" over a
// database that is already in use, which is the one thing the operator most
// needs not to believe.
//
// SQLite is stat'ed before opening on purpose: db.Open CREATES the file, and a
// probe must not bring into existence the very thing it claims to have found.
func detectExistingDB(cfg settings.DB) *existingDBInfo {
	info := &existingDBInfo{}
	switch cfg.Driver {
	case "sqlite", "":
		path := cfg.SQLitePath
		if path == "" {
			return nil
		}
		if st, err := os.Stat(path); err != nil || st.Size() == 0 {
			return nil
		}
		info.Driver, info.Location = "SQLite", path
	case "mariadb", "mysql":
		m := cfg.MariaDB
		if m.Database == "" {
			return nil
		}
		info.Driver = "MariaDB / MySQL"
		info.Location = fmt.Sprintf("%s@%s:%d/%s", m.User, m.Host, m.Port, m.Database)
	default:
		return nil
	}

	conn, err := db.Open(cfg)
	if err != nil {
		return nil
	}
	defer conn.Close()

	// One query answers both questions: a missing table errors out (= not
	// migrated, so there is nothing to keep), and the count is the evidence
	// shown to the operator.
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	if err := conn.QueryRowContext(ctx, `SELECT COUNT(*) FROM unmask_event`).Scan(&info.Events); err != nil {
		return nil
	}
	return info
}

func (h *Handler) AdminSetupIndex(w http.ResponseWriter, r *http.Request) {
	tmpl, err := loadDashboardTemplate()
	if err != nil {
		http.Error(w, "template error", http.StatusInternalServerError)
		return
	}
	// Reconfigure mode: an authenticated superadmin re-running setup.  Keyed on
	// auth ALONE (not setupHasAdmin) so it still holds when the live DB has no
	// admin yet -- e.g. mid-switch to a fresh DB -- instead of falling back to the
	// bootstrap token step.  The wizard starts at the DB step on session-keyed
	// state.
	reconfigure := h.setupSuperadmin(r) != nil
	var step string
	if reconfigure {
		if ws := h.getWizardState(r); ws != nil {
			step = ws.step()
		} else {
			step = "db"
		}
	} else {
		_, step = h.SetupNeeded(r)
		if step == "" {
			// Done.  Redirect anyway as a guard against a race where SetupGate didn't fire.
			http.Redirect(w, r, h.cfg().Server.BasePath+"/admin/", http.StatusFound)
			return
		}
	}
	// Backward navigation: ?step=<earlier-step> lets the user revisit a
	// step they've already passed (= fixing a typo in admin username after
	// reaching the mode step etc.). Only honored when the requested step
	// is strictly earlier than the natural one (= can't skip forward).
	if req := r.URL.Query().Get("step"); req != "" {
		order := map[string]int{"token": 0, "db": 1, "user": 2, "review": 3, "done": 4}
		if order[req] < order[step] && (reconfigure || hasValidSetupToken(r)) {
			step = req
		}
	}
	cur := h.snapshotSettings().DB
	// Start with the saved-on-disk DB config (= bootstrap defaults).  If
	// the wizard state already has DB values entered, overlay them so the
	// form is pre-filled when the user navigates back.
	wstate := h.getWizardState(r)
	if wstate != nil && wstate.DBSet {
		cur = wstate.DB
	}
	// If the query string carries values (= failure round-trip), apply
	// them last so the user sees what they just submitted.
	q := r.URL.Query()
	if v := q.Get("driver"); v != "" {
		cur.Driver = v
	}
	if v := q.Get("sqlite_path"); v != "" {
		cur.SQLitePath = v
	}
	if v := q.Get("mariadb_host"); v != "" {
		cur.MariaDB.Host = v
	}
	if v := q.Get("mariadb_port"); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			cur.MariaDB.Port = n
		}
	}
	if v := q.Get("mariadb_database"); v != "" {
		cur.MariaDB.Database = v
	}
	if v := q.Get("mariadb_user"); v != "" {
		cur.MariaDB.User = v
	}
	// Which driver card renders as selected.  Decided here, not in the
	// template, so the precedence reads as one rule instead of nested
	// conditionals across four elements: an explicit choice the operator just
	// made wins, then the database already in use, then the driver on disk.
	existing := detectExistingDB(h.snapshotSettings().DB)
	driverChoice := "sqlite"
	switch {
	case q.Get("driver") != "":
		driverChoice = q.Get("driver")
	case existing != nil:
		driverChoice = "existing"
	case cur.Driver == "mariadb":
		driverChoice = "mariadb"
	}

	// Build the language picker payload once: ordered list of {code, name}.
	// Order follows i18n.SupportedLangs so the picker's reading order is
	// deterministic across requests.
	langOpts := make([]map[string]string, 0, len(i18n.SupportedLangs))
	for _, l := range i18n.SupportedLangs {
		langOpts = append(langOpts, map[string]string{
			"Code": string(l),
			"Name": i18n.NameOf(l),
		})
	}
	data := map[string]any{
		"Lang":        i18n.Resolve(r),
		"TZ":          resolveTZ(r),
		"BasePath":    h.cfg().Server.BasePath,
		"Version":     h.Version,
		"Step":        step,
		"Error":       q.Get("err"),
		"DB":          cur,
		"LangOptions": langOpts,
		// Non-nil when the configured database is already migrated, which
		// turns the driver choice from "build one" into "keep this or replace
		// it".  Read from the on-disk config, not from `cur`: `cur` may carry
		// values the operator is in the middle of typing for a DIFFERENT
		// database, and the card has to describe the one already in use.
		"ExistingDB":   existing,
		"DriverChoice": driverChoice,
		// Reconfigure: a superadmin re-running setup on a configured install.
		// Drives the "you're reconfiguring" banner, the skip-user option, and
		// the "switching DB doesn't move data / keeps the old DB" warning.
		"Reconfigure": reconfigure,
		// CSRF token for the form hidden fields.  Empty in bootstrap (no session
		// yet, and bootstrap POSTs are token-gated, not CSRF-gated); the logged-in
		// superadmin's token in reconfigure, where the POSTs DO verify CSRF.
		"CSRFToken": CSRFTokenFromRequest(r),
	}
	if step == "user" {
		// Pre-fill the username so it survives a validation-error round-trip
		// (?username=) or a backtrack to this step (wizard state).  The password
		// is *not* round-tripped via HTML (= the field stays blank); the user
		// re-enters it.  Internally wstate.PasswordHash holds the argon2id hash
		// of the previously-entered password until they submit again.
		if u := q.Get("username"); u != "" {
			data["PrefillUsername"] = u
		} else if wstate != nil && wstate.UserSet {
			data["PrefillUsername"] = wstate.Username
		}
	}
	if step == "user" && reconfigure && wstate != nil && wstate.DBSet {
		// Whether the SELECTED target DB already has an admin.  Only then is
		// "skip user creation" valid -- skipping against an empty DB (e.g. a
		// fresh MariaDB you just switched to) would leave no way to log in, so
		// the button is hidden and an admin must be created.
		u, _ := h.targetDBStats(wstate.DB)
		data["TargetHasUser"] = u > 0
		data["TargetUsers"] = u
	}
	if step == "review" && wstate != nil {
		// Final summary screen renders driver + admin for confirmation.
		// Bot-detection posture is configured later in the Operating mode tab so
		// the wizard stays narrowly focused on "make admin reachable".
		data["ReviewDriver"] = wstate.DB.Driver
		data["ReviewSQLitePath"] = wstate.DB.SQLitePath
		data["ReviewMariaDBHost"] = wstate.DB.MariaDB.Host
		data["ReviewMariaDBPort"] = wstate.DB.MariaDB.Port
		data["ReviewMariaDBDB"] = wstate.DB.MariaDB.Database
		data["ReviewMariaDBUser"] = wstate.DB.MariaDB.User
		data["ReviewUsername"] = wstate.Username
		if reconfigure {
			// Show what's already in the target DB so the operator knows whether
			// install will adopt existing data or create a fresh schema.
			u, e := h.targetDBStats(wstate.DB)
			data["TargetUsers"] = u
			data["TargetEvents"] = e
			data["TargetHasData"] = u > 0 || e > 0
			// No-op guard: the wizard ended up pointed at the DB the daemon already
			// runs, adopting its existing admin (no new user).  Installing would
			// rewrite config + hot-swap the live handle for zero net change, so the
			// review step hides the install button and offers a way back instead.
			data["NoChange"] = h.reconfigureNoOp(wstate)
		}
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if err := tmpl.ExecuteTemplate(w, "setup.html", data); err != nil {
		log.Printf("setup render: %v", err)
	}
}

// AdminSetupSaveToken: POST {base}/admin/setup/token — verify the token
// input.  On success, set a session cookie so the user can continue
// through the wizard.
func (h *Handler) AdminSetupSaveToken(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "bad form", http.StatusBadRequest)
		return
	}
	base := h.cfg().Server.BasePath
	expected := readSetupToken()
	if expected == "" {
		// Environment that doesn't need a token (= dev).  Send straight to setup.
		http.Redirect(w, r, base+"/admin/setup/", http.StatusFound)
		return
	}
	got := strings.TrimSpace(r.FormValue("token"))
	if got == "" || subtle.ConstantTimeCompare([]byte(got), []byte(expected)) != 1 {
		http.Redirect(w, r, base+"/admin/setup/?err="+urlEncodeShort("invalid setup token"), http.StatusFound)
		return
	}
	// Verified -> issue a cookie (= the session that drives the rest of the wizard).
	http.SetCookie(w, &http.Cookie{
		Name:     SetupTokenCookieName,
		Value:    expected,
		Path:     base + "/admin/setup",
		HttpOnly: true,
		// Secure on HTTPS so the setup token (= wizard auth) isn't sent in
		// cleartext; matches the session/CSRF cookies.
		Secure:   r.TLS != nil || r.Header.Get("X-Forwarded-Proto") == "https",
		SameSite: http.SameSiteStrictMode,
		MaxAge:   3600, // 1 hour (= long enough to finish the wizard)
	})
	http.Redirect(w, r, base+"/admin/setup/", http.StatusFound)
}

// AdminSetupSaveDB: POST {base}/admin/setup/db — validate the driver /
// connection, but only store the choice in wizard state.  Actual migrate +
// hot-swap happens in AdminSetupInstall (= deferred-commit model so the
// user can navigate back and forth without irreversible side effects).
func (h *Handler) AdminSetupSaveDB(w http.ResponseWriter, r *http.Request) {
	// Bootstrap requires the token; reconfigure is gated by superadmin auth
	// (SetupGate already enforced it).
	if h.setupSuperadmin(r) == nil && !hasValidSetupToken(r) {
		http.Redirect(w, r, h.cfg().Server.BasePath+"/admin/setup/", http.StatusFound)
		return
	}
	if err := r.ParseForm(); err != nil {
		http.Error(w, "bad form", http.StatusBadRequest)
		return
	}
	if !h.setupCSRFOK(w, r) {
		return
	}
	base := h.cfg().Server.BasePath
	lang := i18n.Resolve(r)
	// On failure, round-trip the input values via the query string so the
	// template can repopulate them (= driver / host / port / database /
	// user travel via query.  password is sensitive and is not
	// round-tripped; the user re-enters it.)
	redirErr := func(msg string) {
		q := url.Values{}
		q.Set("err", msg)
		q.Set("driver", strings.TrimSpace(r.FormValue("driver")))
		q.Set("sqlite_path", strings.TrimSpace(r.FormValue("sqlite_path")))
		q.Set("mariadb_host", strings.TrimSpace(r.FormValue("mariadb_host")))
		q.Set("mariadb_port", strings.TrimSpace(r.FormValue("mariadb_port")))
		q.Set("mariadb_database", strings.TrimSpace(r.FormValue("mariadb_database")))
		q.Set("mariadb_user", strings.TrimSpace(r.FormValue("mariadb_user")))
		http.Redirect(w, r, base+"/admin/setup/?"+q.Encode(), http.StatusFound)
	}

	driver := strings.TrimSpace(r.FormValue("driver"))
	// "existing" = keep the database this install is already using.  Detection
	// is re-run here rather than trusted from the form: the rendered page is
	// not the authority on what is on disk, and a posted "existing" against a
	// database that has since gone away must fail rather than commit a config
	// pointing at nothing.
	if driver == "existing" {
		curDB := h.snapshotSettings().DB
		if detectExistingDB(curDB) == nil {
			redirErr(i18n.T(lang, "setup.err.existing_gone"))
			return
		}
		s := h.getWizardState(r)
		if s == nil {
			redirErr("setup session expired; reload and re-enter the token")
			return
		}
		s.DB = curDB
		s.DBSet = true
		touchWizardState(s)
		http.Redirect(w, r, base+"/admin/setup/", http.StatusFound)
		return
	}
	if driver != "sqlite" && driver != "mariadb" {
		redirErr(i18n.T(lang, "setup.err.driver_invalid"))
		return
	}
	cfg := settings.DB{Driver: driver}
	if driver == "sqlite" {
		path := strings.TrimSpace(r.FormValue("sqlite_path"))
		if path == "" {
			path = "/var/lib/unmask/unmask.sqlite"
		}
		cfg.SQLitePath = path
	} else {
		host := strings.TrimSpace(r.FormValue("mariadb_host"))
		if host == "" {
			host = "127.0.0.1"
		}
		port, _ := strconv.Atoi(strings.TrimSpace(r.FormValue("mariadb_port")))
		if port <= 0 {
			port = 3306
		}
		cfg.MariaDB.Host = host
		cfg.MariaDB.Port = port
		cfg.MariaDB.Database = strings.TrimSpace(r.FormValue("mariadb_database"))
		cfg.MariaDB.User = strings.TrimSpace(r.FormValue("mariadb_user"))
		cfg.MariaDB.Password = r.FormValue("mariadb_password")
		// Reconfigure: a blank password field means "keep the current one" (the
		// form shows a placeholder, never the real secret), as long as the
		// current config is already MariaDB so there is one to keep.
		if cfg.MariaDB.Password == "" && h.setupSuperadmin(r) != nil {
			if curDB := h.snapshotSettings().DB; curDB.Driver == "mariadb" {
				cfg.MariaDB.Password = curDB.MariaDB.Password
			}
		}
		if cfg.MariaDB.Database == "" || cfg.MariaDB.User == "" {
			redirErr(i18n.T(lang, "setup.err.mariadb_required"))
			return
		}
	}

	// Connection test only: open + immediately close.  Migrate / hot-swap
	// happen in AdminSetupInstall.  For sqlite this creates an empty file
	// if it didn't exist; harmless, and the install-time migrate will fill
	// in the schema.
	conn, err := db.Open(cfg)
	if err != nil {
		redirErr(i18n.T(lang, "setup.err.connect") + ": " + err.Error())
		return
	}
	_ = conn.Close()

	s := h.getWizardState(r)
	if s == nil {
		redirErr("setup session expired; reload and re-enter the token")
		return
	}
	s.DB = cfg
	s.DBSet = true
	touchWizardState(s)
	http.Redirect(w, r, base+"/admin/setup/", http.StatusFound)
}

// AdminSetupSaveUser: POST {base}/admin/setup/user — validate the admin
// username + password and store them in wizard state.  Actual unmask_user
// row creation happens in AdminSetupInstall.
func (h *Handler) AdminSetupSaveUser(w http.ResponseWriter, r *http.Request) {
	// Bootstrap requires the token; reconfigure is gated by superadmin auth.
	if h.setupSuperadmin(r) == nil && !hasValidSetupToken(r) {
		http.Redirect(w, r, h.cfg().Server.BasePath+"/admin/setup/", http.StatusFound)
		return
	}
	if err := r.ParseForm(); err != nil {
		http.Error(w, "bad form", http.StatusBadRequest)
		return
	}
	if !h.setupCSRFOK(w, r) {
		return
	}
	base := h.cfg().Server.BasePath
	redirErr := func(msg string) {
		q := url.Values{}
		q.Set("err", msg)
		// Round-trip the entered username so a validation error doesn't wipe it
		// (the password is intentionally not round-tripped; the user re-enters it).
		if u := strings.TrimSpace(r.FormValue("username")); u != "" {
			q.Set("username", u)
		}
		http.Redirect(w, r, base+"/admin/setup/?"+q.Encode(), http.StatusFound)
	}

	// Reconfigure: "skip" keeps the target DB's existing admin instead of
	// creating one (only an authenticated superadmin may skip; bootstrap must
	// create the first user).  Install re-validates the target DB has a user.
	if r.FormValue("action") == "skip" && h.setupSuperadmin(r) != nil {
		s := h.getWizardState(r)
		if s == nil || !s.DBSet {
			redirErr("complete the DB step first")
			return
		}
		s.UserSet = false
		s.UserSkipped = true
		touchWizardState(s)
		http.Redirect(w, r, base+"/admin/setup/", http.StatusFound)
		return
	}

	lang := i18n.Resolve(r)
	username := strings.TrimSpace(r.FormValue("username"))
	password := r.FormValue("password")
	confirm := r.FormValue("password_confirm")
	if username == "" || password == "" {
		redirErr(i18n.T(lang, "setup.err.user_required"))
		return
	}
	if password != confirm {
		redirErr(i18n.T(lang, "setup.err.password_mismatch"))
		return
	}
	if err := user.ValidatePassword(password); err != nil {
		redirErr(err.Error())
		return
	}

	s := h.getWizardState(r)
	if s == nil {
		redirErr("setup session expired; reload and re-enter the token")
		return
	}
	// Guard against server restart mid-wizard: in-memory state was lost,
	// so DBSet is false even though the form looks like step 3.  Send the
	// user back to the DB step with a clear notice instead of silently
	// jumping them around.
	if !s.DBSet {
		redirErr("setup session was reset (likely an admin restart); please complete the DB step again")
		return
	}
	// Reconfigure: reject a username that already exists in the target DB now
	// (the unique constraint would otherwise only surface at install).  The
	// operator can pick a different name or use Skip to keep the existing admin.
	if h.setupSuperadmin(r) != nil && h.targetDBHasUsername(s.DB, username) {
		redirErr(i18n.T(lang, "setup.err.username_taken"))
		return
	}
	s.Username = username
	// Hash immediately and discard the plaintext so the wizard never holds an
	// operator password in memory for the rest of its TTL (AUTH-7).
	pwHash, err := user.HashPassword(password)
	if err != nil {
		redirErr("hash password: " + err.Error())
		return
	}
	s.PasswordHash = pwHash
	s.UserSet = true
	touchWizardState(s)
	http.Redirect(w, r, base+"/admin/setup/", http.StatusFound)
}

// AdminSetupInstall: POST {base}/admin/setup/install — atomic commit of
// everything the wizard collected.  Steps in order: migrate DB, create
// admin user, apply protection-mode preset, persist config.yml, hot-swap
// runtime state, remove the setup token (= seals the wizard), drop the
// in-flight wizard state.  Any error before the token removal leaves the
// wizard re-runnable.
func (h *Handler) AdminSetupInstall(w http.ResponseWriter, r *http.Request) {
	base := h.cfg().Server.BasePath
	redirErr := func(msg string) {
		http.Redirect(w, r, base+"/admin/setup/?err="+urlEncodeShort(msg), http.StatusFound)
	}
	// Reconfigure: an authenticated superadmin re-running setup (SetupGate already
	// enforced the auth).  Keyed on auth ALONE so it still holds when the live DB
	// has no admin (mid-switch to a fresh DB); a tokenless bootstrap install
	// instead requires the setup token and refuses to run against a provisioned DB.
	reconfigure := h.setupSuperadmin(r) != nil
	if !reconfigure {
		if !hasValidSetupToken(r) {
			http.Redirect(w, r, base+"/admin/setup/", http.StatusFound)
			return
		}
		// Defense in depth: never re-install against an already-provisioned
		// instance via the bootstrap path.  If the live DB already has a user,
		// setup was completed before (a stale token slipped through) --
		// re-installing would migrate a fresh DB and rewrite config.yml's DB
		// block to SQLite, orphaning the real backend.  Clear the stale token
		// and bounce to the dashboard.
		if h.DB != nil {
			ctx, cancel := context.WithTimeout(r.Context(), 2*time.Second)
			var n int
			err := h.DB.QueryRowContext(ctx, `SELECT COUNT(*) FROM unmask_user`).Scan(&n)
			cancel()
			if err == nil && n > 0 {
				removeSetupToken()
				http.Redirect(w, r, base+"/admin/", http.StatusFound)
				return
			}
		}
	}
	// Reconfigure installs carry a session, so enforce CSRF (bootstrap installs
	// are protected by the unguessable setup token instead).
	_ = r.ParseForm()
	if !h.setupCSRFOK(w, r) {
		return
	}
	lang := i18n.Resolve(r)
	stateKey := h.wizardStateKey(r)
	s := wizardStateForKey(stateKey)
	if s == nil || !s.DBSet {
		redirErr(i18n.T(lang, "setup.err.incomplete_db"))
		return
	}
	// The admin-user step is mandatory on a bootstrap install but optional when
	// reconfiguring -- the target DB may already have an admin (validated below).
	if !reconfigure && !s.UserSet {
		redirErr(i18n.T(lang, "setup.err.incomplete_all"))
		return
	}
	// No-op reconfigure: the wizard is pointed at the DB the daemon already runs
	// and creates no new admin (it adopts the existing one).  Installing would
	// rewrite config.yml and hot-swap the live handle for zero net change, so skip
	// the work and return to the dashboard.  The review step normally hides the
	// button for this case; this guards a direct POST.
	if reconfigure && h.reconfigureNoOp(s) {
		http.Redirect(w, r, base+"/admin/", http.StatusFound)
		return
	}

	setupMu.Lock()
	defer setupMu.Unlock()

	// 1. open + migrate DB.  When the wizard keeps the DB the daemon already
	// booted with (the common SQLite-default path), REUSE the live connection
	// rather than opening a second handle and closing the first: the background
	// workers (events flusher, aggregate, prune, nginxlog, ban) hold the boot
	// handle, so closing it under them silently drops every /api/check event
	// until a restart.  A different DB (e.g. switching to MariaDB) still needs a
	// fresh handle -- and a daemon restart, which the done page now demands.
	var conn *db.DB
	if h.DB != nil && s.DB == h.cfg().DB {
		conn = h.DB
	} else {
		c, oerr := db.Open(s.DB)
		if oerr != nil {
			redirErr("db connect: " + oerr.Error())
			return
		}
		conn = c
	}
	if err := db.Migrate(conn); err != nil {
		if conn != h.DB {
			_ = conn.Close()
		}
		redirErr("db migrate: " + err.Error())
		return
	}
	// 2. create admin user (= superadmin), or skip when reconfiguring and the
	// target DB already has one (else the operator would be locked out).
	repo := user.New(conn)
	if s.UserSet {
		if _, err := repo.CreateWithHash(r.Context(), s.Username, s.PasswordHash, user.RoleSuperadmin); err != nil {
			if conn != h.DB {
				_ = conn.Close()
			}
			redirErr("create user: " + err.Error())
			return
		}
	} else {
		// User step skipped (reconfigure only): the selected DB must already
		// hold an admin, or there'd be no way to log in afterward.
		n, cerr := repo.Count(r.Context())
		if cerr != nil {
			if conn != h.DB {
				_ = conn.Close()
			}
			redirErr("count users in selected DB: " + cerr.Error())
			return
		}
		if n == 0 {
			if conn != h.DB {
				_ = conn.Close()
			}
			// The target DB has no admin to keep, so "skip" is invalid.  Rather
			// than a dead-end error, send the operator back to the user step --
			// where the "new/empty DB: create an admin" hint shows in their
			// language -- and clear the skip flag so that step is the natural one.
			s.UserSkipped = false
			touchWizardState(s)
			http.Redirect(w, r, base+"/admin/setup/?step=user", http.StatusFound)
			return
		}
	}
	// 3. apply protection-mode preset onto current settings and persist
	cur, err := settings.Load(h.ConfigPath)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			// No config file yet (genuinely fresh): an empty template is the
			// only option -- the install flow's config-init normally writes one
			// (with bv_secret) before the wizard runs.
			cur = settings.Settings{}
		} else {
			// The file EXISTS but won't load (unreadable / unparseable).  Do NOT
			// fall back to an empty template: Save() marshals every field, so it
			// would clobber the real config -- wiping secret.bv_secret and looping
			// every visitor on the challenge after the next restart (the
			// settings.Load-then-Save hazard).  Abort and surface the error.
			if conn != h.DB {
				_ = conn.Close()
			}
			redirErr("read admin.yml (exists but won't load): " + err.Error())
			return
		}
	}
	cur.DB = s.DB
	// Completing the wizard means the operator is looking at THIS release, so
	// stamp it as seen: this baselines the settings UI's "NEW since your last
	// save" badge to this version, so only what later releases add is badged.
	// (Presets themselves are active from the release that ships them; the
	// stamp no longer gates rendering.)  Guarded so a dev build ("vdev",
	// unparseable) cannot overwrite a real recorded version.
	if v := "v" + h.Version; nginxconf.VersionParseable(v) {
		cur.Nginx.SeenVersion = v
	}
	if err := settings.Save(cur, h.ConfigPath); err != nil {
		if conn != h.DB {
			_ = conn.Close()
		}
		redirErr("save admin.yml: " + err.Error())
		return
	}
	// 4. hot-swap runtime state
	old := h.DB
	h.DB = conn
	if h.UserRepo != nil {
		h.UserRepo.DB = conn
	} else {
		h.UserRepo = repo
	}
	h.updateSettingsInMemory(func(live *settings.Settings) {
		live.DB = s.DB
		// Setup wizard only touches the global Default record (= per-site
		// overrides are introduced later via the settings tab).
		live.Challenge.Default.ObserveOnly = cur.Challenge.Default.ObserveOnly
	})
	if old != nil && old != conn {
		_ = old.Close()
	}
	// 5. seal the wizard.  removeSetupToken is a no-op when reconfiguring (the
	// bootstrap token is already gone); drop the in-flight state by the same
	// mode-aware key it was stored under (stateKey was captured pre-swap).
	removeSetupToken()
	dropWizardState(stateKey)
	// A DB switch (e.g. to MariaDB) opened a fresh handle and closed the boot
	// one; the background workers are still bound to the old handle, so only a
	// restart re-binds them.  Flag it so the done page makes the restart
	// mandatory instead of optional.  An unchanged DB reused the live handle and
	// needs no restart.
	done := base + "/admin/setup/done"
	if old != conn {
		done += "?restart=1"
	}
	http.Redirect(w, r, done, http.StatusFound)
	if old != conn {
		// A DB switch orphaned the background workers (hourly aggregate / prune /
		// event flusher still hold the now-closed boot handle), which silently
		// breaks the funnel + serve recording until a restart.  Re-exec so they
		// rebind to the new DB -- no manual restart needed.
		scheduleReexec()
	}
}

// reexecOnce guards the post-setup self-restart so a page refresh can't fire it twice.
var reexecOnce sync.Once

// scheduleReexec re-launches the daemon in place a few seconds after a DB switch,
// once the setup-done response has flushed.  syscall.Exec keeps the PID, so the
// sysv pidfile / systemd MainPID stay valid.  This rebinds the background workers
// (hourly aggregate / prune / event flusher) that were left on the closed boot DB
// handle.  On failure it is a no-op (the done page still names a manual restart).
func scheduleReexec() {
	reexecOnce.Do(func() {
		go func() {
			time.Sleep(3 * time.Second) // let the redirect + done page flush first
			exe, err := os.Executable()
			if err != nil {
				exe = os.Args[0]
			}
			log.Printf("setup: re-exec %s to rebind background workers to the new DB", exe)
			if err := syscall.Exec(exe, os.Args, os.Environ()); err != nil {
				log.Printf("setup: re-exec failed (%v); restart the daemon manually", err)
			}
		}()
	})
}

// AdminSetupDone: GET {base}/admin/setup/done — completion screen (= links to login).
func (h *Handler) AdminSetupDone(w http.ResponseWriter, r *http.Request) {
	tmpl, err := loadDashboardTemplate()
	if err != nil {
		http.Error(w, "template error", http.StatusInternalServerError)
		return
	}
	data := map[string]any{
		"Lang":            i18n.Resolve(r),
		"BasePath":        h.cfg().Server.BasePath,
		"Version":         h.Version,
		"Step":            "done",
		"RestartRequired": r.URL.Query().Get("restart") == "1",
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if err := tmpl.ExecuteTemplate(w, "setup.html", data); err != nil {
		log.Printf("setup done render: %v", err)
	}
}

// urlEncodeShort: URL-escape the err string for redirects (= written
// here instead of going through net/url so we don't pull in another
// import).
func urlEncodeShort(s string) string {
	if len(s) > 200 {
		s = s[:200]
	}
	return (&urlEnc{}).encode(s)
}

type urlEnc struct{}

func (*urlEnc) encode(s string) string {
	out := make([]byte, 0, len(s)*3)
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c >= '0' && c <= '9', c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z',
			c == '-', c == '_', c == '.', c == '~':
			out = append(out, c)
		default:
			const hex = "0123456789ABCDEF"
			out = append(out, '%', hex[c>>4], hex[c&0xF])
		}
	}
	return string(out)
}
