// Install wizard (= the first-run flow modeled after Cacti / Zabbix / Nextcloud).
//
// Right after start: any `/admin/*` access -> redirect to `/admin/setup/`
// if setup is needed.  After setup completes, hitting `/admin/setup/*`
// redirects to `/admin/` (= prevent re-setup).
//
// Steps:
//   1. welcome
//   2. choose DB driver (sqlite / mariadb) + connection test + save admin.yml + migration
//   3. create administrator account (= the first row in unmask_user)
//   4. done -> on to login
//
// setupNeeded() returns true when any of:
//   - h.DB == nil                (= initial start failed to connect)
//   - unmask_user table missing  (= migration not run)
//   - 0 users in the DB          (= no admin yet)
package handlers

import (
	"context"
	"log"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/unmask-sh/unmask/admin/internal/db"
	"github.com/unmask-sh/unmask/admin/internal/i18n"
	"github.com/unmask-sh/unmask/admin/internal/settings"
	"github.com/unmask-sh/unmask/admin/internal/user"
)

// setupMu: serializes DB swap / settings save.
var setupMu sync.Mutex

// SetupNeeded: decide whether to send the user to the setup wizard.
//
// step:
//   "db"   : DB not connected OR table missing -> step 2 (DB picker)
//   "user" : DB OK but 0 rows in unmask_user   -> step 3 (create admin user)
//   ""     : setup not needed
//
// step != "" means "setup is needed" -> route to the wizard.

// SetupTokenPath: path to a token file used to prevent a third party from
// completing setup ahead of the admin.  Generated by the rpm/deb/apk
// postinstall as 0600 unmask:unmask, so only someone who can
// `sudo cat /etc/unmask/.setup-token` (= a sudoer on the host) can
// finish setup.  The file is deleted on completion so the wizard can't
// be re-run.
const SetupTokenPath = "/etc/unmask/.setup-token"
const SetupTokenCookieName = "unmask_setup_token"

// readSetupToken: read the token from the file.  Empty / unreadable -> "".
func readSetupToken() string {
	b, err := os.ReadFile(SetupTokenPath)
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(b))
}

// hasValidSetupToken: does the current request carry a valid token cookie?
// Docker containers and local dev may not have the token file at all; in
// that case absence of a token means "open setup" (= backward-compatible
// / non-destructive).  Production rpm installs always generate the
// token via postinstall, so verification is enforced.
func hasValidSetupToken(r *http.Request) bool {
	expected := readSetupToken()
	if expected == "" {
		return true // token not installed = open setup (= dev / docker / manual install)
	}
	c, err := r.Cookie(SetupTokenCookieName)
	if err != nil {
		return false
	}
	return c.Value == expected
}

// removeSetupToken: delete the token file on setup completion so the
// wizard can no longer be triggered.
func removeSetupToken() {
	if err := os.Remove(SetupTokenPath); err != nil && !os.IsNotExist(err) {
		log.Printf("setup token remove: %v", err)
	}
}

func (h *Handler) SetupNeeded(r *http.Request) (needed bool, step string) {
	if h == nil {
		return false, ""
	}
	// Wizard phase = the setup token file is still present.  Step comes
	// from in-flight wizard state (= deferred-commit model).  The token
	// file is removed at the end of AdminSetupInstall.
	if _, err := os.Stat(SetupTokenPath); err == nil {
		// Without a verified token cookie, we can't read wizard state — go
		// to the token step.
		if !hasValidSetupToken(r) {
			return true, "token"
		}
		s := getWizardState(r)
		if s == nil {
			return true, "token"
		}
		return true, s.step()
	}
	// Post-install fallback: anything that genuinely needs setup attention
	// (= no DB connection, no admin user) routes back to the wizard.  In
	// practice, install removes the token first and these branches don't
	// fire — but they protect against partial state.
	if h.DB == nil {
		return true, "db"
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()
	var n int
	row := h.DB.QueryRowContext(ctx, `SELECT COUNT(*) FROM unmask_user`)
	if err := row.Scan(&n); err != nil {
		return true, "db"
	}
	if n == 0 {
		return true, "user"
	}
	return false, ""
}

// SetupGate: setup-wizard middleware.  When setup is needed, redirect
// everything except the setup endpoints to /admin/setup/.  Once setup
// completes, hitting /admin/setup/* sends you back to /admin/ (= can't
// re-run the wizard).
func (h *Handler) SetupGate(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		needed, _ := h.SetupNeeded(r)
		base := h.Settings.Server.BasePath
		isSetupPath := strings.HasPrefix(r.URL.Path, base+"/admin/setup")
		// done + on a setup endpoint -> kick to /admin/.
		if !needed && isSetupPath {
			http.Redirect(w, r, base+"/admin/", http.StatusFound)
			return
		}
		// still needed + on a different endpoint -> redirect to setup.
		if needed && !isSetupPath {
			http.Redirect(w, r, base+"/admin/setup/", http.StatusFound)
			return
		}
		next(w, r)
	}
}

// AdminSetupIndex: GET {base}/admin/setup/  — render the current step.
//
// step order: token -> db -> user -> done.
// token only fires when the file exists AND the cookie isn't verified
// yet.  When the file is absent (= dev/docker), skip token and go
// straight to the db step.
func (h *Handler) AdminSetupIndex(w http.ResponseWriter, r *http.Request) {
	tmpl, err := loadDashboardTemplate()
	if err != nil {
		http.Error(w, "template error", http.StatusInternalServerError)
		return
	}
	_, step := h.SetupNeeded(r)
	if step == "" {
		// Done.  Redirect anyway as a guard against a race where SetupGate didn't fire.
		http.Redirect(w, r, h.Settings.Server.BasePath+"/admin/", http.StatusFound)
		return
	}
	// Backward navigation: ?step=<earlier-step> lets the user revisit a
	// step they've already passed (= fixing a typo in admin username after
	// reaching the mode step etc.). Only honored when the requested step
	// is strictly earlier than the natural one (= can't skip forward).
	if req := r.URL.Query().Get("step"); req != "" {
		order := map[string]int{"token": 0, "db": 1, "user": 2, "review": 3, "done": 4}
		if order[req] < order[step] && hasValidSetupToken(r) {
			step = req
		}
	}
	cur := h.snapshotSettings().DB
	// Start with the saved-on-disk DB config (= bootstrap defaults).  If
	// the wizard state already has DB values entered, overlay them so the
	// form is pre-filled when the user navigates back.
	wstate := getWizardState(r)
	if wstate != nil && wstate.DBSet {
		cur = wstate.DB
	}
	// If the query string carries values (= failure round-trip), apply
	// them last so the user sees what they just submitted.
	q := r.URL.Query()
	if v := q.Get("driver"); v != "" {
		cur.Driver = v
	}
	if v := q.Get("sqlite_path"); v != "" {
		cur.SQLitePath = v
	}
	if v := q.Get("mariadb_host"); v != "" {
		cur.MariaDB.Host = v
	}
	if v := q.Get("mariadb_port"); v != "" {
		if n, err := strconv.Atoi(v); err == nil {
			cur.MariaDB.Port = n
		}
	}
	if v := q.Get("mariadb_database"); v != "" {
		cur.MariaDB.Database = v
	}
	if v := q.Get("mariadb_user"); v != "" {
		cur.MariaDB.User = v
	}
	// Build the language picker payload once: ordered list of {code, name}.
	// Order follows i18n.SupportedLangs so the picker's reading order is
	// deterministic across requests.
	langOpts := make([]map[string]string, 0, len(i18n.SupportedLangs))
	for _, l := range i18n.SupportedLangs {
		langOpts = append(langOpts, map[string]string{
			"Code": string(l),
			"Name": i18n.NameOf(l),
		})
	}
	data := map[string]any{
		"Lang":         i18n.Resolve(r),
		"TZ":           resolveTZ(r),
		"BasePath":     h.Settings.Server.BasePath,
		"Version":      h.Version,
		"Step":         step,
		"Error":        q.Get("err"),
		"DB":           cur,
		"LangOptions":  langOpts,
	}
	if step == "user" && wstate != nil && wstate.UserSet {
		// Pre-fill the username so the user can review / edit on backtrack.
		// The password is *not* round-tripped via HTML (= the field stays
		// blank); the user re-enters it.  Internally wstate.Password is
		// still the previously-entered value until they submit again.
		data["PrefillUsername"] = wstate.Username
	}
	if step == "review" && wstate != nil {
		// Final summary screen renders driver + admin for confirmation.
		// Bot-detection posture is configured later in the 動作モード tab so
		// the wizard stays narrowly focused on "make admin reachable".
		data["ReviewDriver"] = wstate.DB.Driver
		data["ReviewSQLitePath"] = wstate.DB.SQLitePath
		data["ReviewMariaDBHost"] = wstate.DB.MariaDB.Host
		data["ReviewMariaDBPort"] = wstate.DB.MariaDB.Port
		data["ReviewMariaDBDB"] = wstate.DB.MariaDB.Database
		data["ReviewMariaDBUser"] = wstate.DB.MariaDB.User
		data["ReviewUsername"] = wstate.Username
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if err := tmpl.ExecuteTemplate(w, "setup.html", data); err != nil {
		log.Printf("setup render: %v", err)
	}
}

// AdminSetupSaveToken: POST {base}/admin/setup/token — verify the token
// input.  On success, set a session cookie so the user can continue
// through the wizard.
func (h *Handler) AdminSetupSaveToken(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "bad form", http.StatusBadRequest)
		return
	}
	base := h.Settings.Server.BasePath
	expected := readSetupToken()
	if expected == "" {
		// Environment that doesn't need a token (= dev).  Send straight to setup.
		http.Redirect(w, r, base+"/admin/setup/", http.StatusFound)
		return
	}
	got := strings.TrimSpace(r.FormValue("token"))
	if got == "" || got != expected {
		http.Redirect(w, r, base+"/admin/setup/?err="+urlEncodeShort("invalid setup token"), http.StatusFound)
		return
	}
	// Verified -> issue a cookie (= the session that drives the rest of the wizard).
	http.SetCookie(w, &http.Cookie{
		Name:     SetupTokenCookieName,
		Value:    expected,
		Path:     base + "/admin/setup",
		HttpOnly: true,
		SameSite: http.SameSiteStrictMode,
		MaxAge:   3600, // 1 hour (= long enough to finish the wizard)
	})
	http.Redirect(w, r, base+"/admin/setup/", http.StatusFound)
}

// AdminSetupSaveDB: POST {base}/admin/setup/db — validate the driver /
// connection, but only store the choice in wizard state.  Actual migrate +
// hot-swap happens in AdminSetupInstall (= deferred-commit model so the
// user can navigate back and forth without irreversible side effects).
func (h *Handler) AdminSetupSaveDB(w http.ResponseWriter, r *http.Request) {
	if !hasValidSetupToken(r) {
		http.Redirect(w, r, h.Settings.Server.BasePath+"/admin/setup/", http.StatusFound)
		return
	}
	if err := r.ParseForm(); err != nil {
		http.Error(w, "bad form", http.StatusBadRequest)
		return
	}
	base := h.Settings.Server.BasePath
	// On failure, round-trip the input values via the query string so the
	// template can repopulate them (= driver / host / port / database /
	// user travel via query.  password is sensitive and is not
	// round-tripped; the user re-enters it.)
	redirErr := func(msg string) {
		q := url.Values{}
		q.Set("err", msg)
		q.Set("driver", strings.TrimSpace(r.FormValue("driver")))
		q.Set("sqlite_path", strings.TrimSpace(r.FormValue("sqlite_path")))
		q.Set("mariadb_host", strings.TrimSpace(r.FormValue("mariadb_host")))
		q.Set("mariadb_port", strings.TrimSpace(r.FormValue("mariadb_port")))
		q.Set("mariadb_database", strings.TrimSpace(r.FormValue("mariadb_database")))
		q.Set("mariadb_user", strings.TrimSpace(r.FormValue("mariadb_user")))
		http.Redirect(w, r, base+"/admin/setup/?"+q.Encode(), http.StatusFound)
	}

	driver := strings.TrimSpace(r.FormValue("driver"))
	if driver != "sqlite" && driver != "mariadb" {
		redirErr("driver must be sqlite or mariadb")
		return
	}
	cfg := settings.DB{Driver: driver}
	if driver == "sqlite" {
		path := strings.TrimSpace(r.FormValue("sqlite_path"))
		if path == "" {
			path = "/var/lib/unmask/unmask.sqlite"
		}
		cfg.SQLitePath = path
	} else {
		host := strings.TrimSpace(r.FormValue("mariadb_host"))
		if host == "" {
			host = "127.0.0.1"
		}
		port, _ := strconv.Atoi(strings.TrimSpace(r.FormValue("mariadb_port")))
		if port <= 0 {
			port = 3306
		}
		cfg.MariaDB.Host = host
		cfg.MariaDB.Port = port
		cfg.MariaDB.Database = strings.TrimSpace(r.FormValue("mariadb_database"))
		cfg.MariaDB.User = strings.TrimSpace(r.FormValue("mariadb_user"))
		cfg.MariaDB.Password = r.FormValue("mariadb_password")
		if cfg.MariaDB.Database == "" || cfg.MariaDB.User == "" {
			redirErr("MariaDB host/database/user are required")
			return
		}
	}

	// Connection test only: open + immediately close.  Migrate / hot-swap
	// happen in AdminSetupInstall.  For sqlite this creates an empty file
	// if it didn't exist; harmless, and the install-time migrate will fill
	// in the schema.
	conn, err := db.Open(cfg)
	if err != nil {
		redirErr("connect: " + err.Error())
		return
	}
	_ = conn.Close()

	s := getWizardState(r)
	if s == nil {
		redirErr("setup session expired; reload and re-enter the token")
		return
	}
	s.DB = cfg
	s.DBSet = true
	touchWizardState(s)
	http.Redirect(w, r, base+"/admin/setup/", http.StatusFound)
}

// AdminSetupSaveUser: POST {base}/admin/setup/user — validate the admin
// username + password and store them in wizard state.  Actual unmask_user
// row creation happens in AdminSetupInstall.
func (h *Handler) AdminSetupSaveUser(w http.ResponseWriter, r *http.Request) {
	if !hasValidSetupToken(r) {
		http.Redirect(w, r, h.Settings.Server.BasePath+"/admin/setup/", http.StatusFound)
		return
	}
	if err := r.ParseForm(); err != nil {
		http.Error(w, "bad form", http.StatusBadRequest)
		return
	}
	base := h.Settings.Server.BasePath
	redirErr := func(msg string) {
		http.Redirect(w, r, base+"/admin/setup/?err="+urlEncodeShort(msg), http.StatusFound)
	}

	username := strings.TrimSpace(r.FormValue("username"))
	password := r.FormValue("password")
	confirm := r.FormValue("password_confirm")
	if username == "" || password == "" {
		redirErr("username and password are required")
		return
	}
	if password != confirm {
		redirErr("password confirmation mismatch")
		return
	}
	if len(password) < 8 {
		redirErr("password must be at least 8 characters")
		return
	}

	s := getWizardState(r)
	if s == nil {
		redirErr("setup session expired; reload and re-enter the token")
		return
	}
	// Guard against server restart mid-wizard: in-memory state was lost,
	// so DBSet is false even though the form looks like step 3.  Send the
	// user back to the DB step with a clear notice instead of silently
	// jumping them around.
	if !s.DBSet {
		redirErr("setup session was reset (likely an admin restart); please complete the DB step again")
		return
	}
	s.Username = username
	s.Password = password
	s.UserSet = true
	touchWizardState(s)
	http.Redirect(w, r, base+"/admin/setup/", http.StatusFound)
}

// AdminSetupInstall: POST {base}/admin/setup/install — atomic commit of
// everything the wizard collected.  Steps in order: migrate DB, create
// admin user, apply protection-mode preset, persist config.yml, hot-swap
// runtime state, remove the setup token (= seals the wizard), drop the
// in-flight wizard state.  Any error before the token removal leaves the
// wizard re-runnable.
func (h *Handler) AdminSetupInstall(w http.ResponseWriter, r *http.Request) {
	if !hasValidSetupToken(r) {
		http.Redirect(w, r, h.Settings.Server.BasePath+"/admin/setup/", http.StatusFound)
		return
	}
	base := h.Settings.Server.BasePath
	redirErr := func(msg string) {
		http.Redirect(w, r, base+"/admin/setup/?err="+urlEncodeShort(msg), http.StatusFound)
	}
	s := getWizardState(r)
	if s == nil || !s.DBSet || !s.UserSet {
		redirErr("setup session incomplete; complete every step before installing")
		return
	}

	setupMu.Lock()
	defer setupMu.Unlock()

	// 1. open + migrate DB
	conn, err := db.Open(s.DB)
	if err != nil {
		redirErr("db connect: " + err.Error())
		return
	}
	if err := db.Migrate(conn); err != nil {
		_ = conn.Close()
		redirErr("db migrate: " + err.Error())
		return
	}
	// 2. create admin user (= superadmin)
	repo := user.New(conn)
	if _, err := repo.Create(r.Context(), s.Username, s.Password, user.RoleSuperadmin); err != nil {
		_ = conn.Close()
		redirErr("create user: " + err.Error())
		return
	}
	// 3. apply protection-mode preset onto current settings and persist
	cur, err := settings.Load(h.ConfigPath)
	if err != nil {
		// admin.yml missing -> start from an empty template.
		cur = settings.Settings{}
	}
	cur.DB = s.DB
	if err := settings.Save(cur, h.ConfigPath); err != nil {
		_ = conn.Close()
		redirErr("save admin.yml: " + err.Error())
		return
	}
	// 4. hot-swap runtime state
	old := h.DB
	h.DB = conn
	if h.UserRepo != nil {
		h.UserRepo.DB = conn
	} else {
		h.UserRepo = repo
	}
	settingsMu.Lock()
	h.Settings.DB = s.DB
	h.Settings.Nginx.ChallengeTargets.All = cur.Nginx.ChallengeTargets.All
	h.Settings.Challenge.ObserveOnly = cur.Challenge.ObserveOnly
	settingsMu.Unlock()
	if old != nil && old != conn {
		_ = old.Close()
	}
	// 5. seal the wizard
	tokenValue := ""
	if c, err := r.Cookie(SetupTokenCookieName); err == nil {
		tokenValue = c.Value
	}
	removeSetupToken()
	if tokenValue != "" {
		dropWizardState(tokenValue)
	}
	http.Redirect(w, r, base+"/admin/setup/done", http.StatusFound)
}

// AdminSetupDone: GET {base}/admin/setup/done — completion screen (= links to login).
func (h *Handler) AdminSetupDone(w http.ResponseWriter, r *http.Request) {
	tmpl, err := loadDashboardTemplate()
	if err != nil {
		http.Error(w, "template error", http.StatusInternalServerError)
		return
	}
	data := map[string]any{
		"Lang":     i18n.Resolve(r),
		"BasePath": h.Settings.Server.BasePath,
		"Version":  h.Version,
		"Step":     "done",
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if err := tmpl.ExecuteTemplate(w, "setup.html", data); err != nil {
		log.Printf("setup done render: %v", err)
	}
}

// urlEncodeShort: URL-escape the err string for redirects (= written
// here instead of going through net/url so we don't pull in another
// import).
func urlEncodeShort(s string) string {
	if len(s) > 200 {
		s = s[:200]
	}
	return (&urlEnc{}).encode(s)
}

type urlEnc struct{}

func (*urlEnc) encode(s string) string {
	out := make([]byte, 0, len(s)*3)
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c >= '0' && c <= '9', c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z',
			c == '-', c == '_', c == '.', c == '~':
			out = append(out, c)
		default:
			const hex = "0123456789ABCDEF"
			out = append(out, '%', hex[c>>4], hex[c&0xF])
		}
	}
	return string(out)
}
