package communitybans

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// The legacy on-disk WriteDocument/ReadDocument pair (= persisted
// community-bans-doc.json) was retired in favour of Client.cachedDoc /
// Client.GetCachedDoc().  nginx never read the file, and admin restart is
// rare enough that an in-memory cache is sufficient.

// ensureMapPlaceholders lays down empty community-bans map files in dir when
// they do not exist yet, so http.inc's `include community-bans-*.map` directives
// resolve before the very first successful pull.  A later pull overwrites them;
// the existence check means a populated map is never clobbered.  This is what
// keeps `nginx -t` (and nginx startup) from aborting on a fresh install whose
// first fetch fails -- e.g. the hub is unreachable or the box is offline.
func ensureMapPlaceholders(dir string) {
	if dir == "" {
		return
	}
	if _, err := os.Stat(filepath.Join(dir, MapFileIPJA4)); os.IsNotExist(err) {
		_ = WriteMapFiles(FeedDocument{GeneratedAt: time.Now().Unix(), Version: 2}, dir)
	}
}

// WriteMapFiles: split feed entries across 3 nginx map snippets and atomic-write.
//
// Output:
//
//	community-bans-ipja4.map  ← match=ip_ja4  : `"<ip>:<ja4>" 1;`
//	community-bans-ja4.map    ← match=ja4_only: `"<ja4>"      1;`
//	community-bans-ip.map     ← match=ip_only : `"<ip>"       1;`
//
// nginx includes them via map ${key} ${var} { default 0; include ...; } to
// drive the hit check.
//
// Always generates all 3 files even on empty feed (= avoids nginx startup
// failure on missing include).
func WriteMapFiles(doc FeedDocument, dir string) error {
	if dir == "" {
		return fmt.Errorf("WriteMapFiles: empty dir")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}

	now := time.Now().Unix()

	var ipja4, ja4, ip []string
	v2 := doc.Version >= 2
	for _, e := range doc.Entries {
		if e.ExpiresAt > 0 && e.ExpiresAt < now {
			continue
		}
		// v2 feed carries Promoted: skip non-promoted entries (= score 1-2,
		// browse-only) from the nginx map files.  v1 feeds (= no Promoted
		// field) treat every entry as enforceable.
		if v2 && !e.Promoted {
			continue
		}
		ipv := strings.TrimSpace(e.IP)
		j := strings.TrimSpace(e.JA4)
		switch e.Match {
		case MatchIPJA4:
			if ipv == "" || j == "" {
				continue
			}
			ipja4 = append(ipja4, fmt.Sprintf("%q 1;", ipv+":"+j))
		case MatchJA4:
			if j == "" {
				continue
			}
			ja4 = append(ja4, fmt.Sprintf("%q 1;", j))
		case MatchIPOnly:
			if ipv == "" {
				continue
			}
			ip = append(ip, fmt.Sprintf("%q 1;", ipv))
		}
	}
	sort.Strings(ipja4)
	sort.Strings(ja4)
	sort.Strings(ip)

	if err := atomicWriteLines(filepath.Join(dir, MapFileIPJA4), ipja4); err != nil {
		return err
	}
	if err := atomicWriteLines(filepath.Join(dir, MapFileJA4), ja4); err != nil {
		return err
	}
	if err := atomicWriteLines(filepath.Join(dir, MapFileIP), ip); err != nil {
		return err
	}
	return nil
}

// atomicWriteLines: atomic via tmp file + rename.  Sorted duplicates are uniq'd.
func atomicWriteLines(path string, lines []string) error {
	var b strings.Builder
	b.WriteString("# generated by unmask communitybans. DO NOT EDIT.\n")
	last := ""
	for _, l := range lines {
		if l == last {
			continue
		}
		b.WriteString(l)
		b.WriteByte('\n')
		last = l
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("rename %s → %s: %w", tmp, path, err)
	}
	return nil
}
