#!/bin/bash
# 58: the community feed enforces on BOTH wires, at the action the operator picked.
#
# The feed used to be enforced by nginx map lookups alone, which meant a
# forward-auth deployment (Apache, or nginx without the module) pulled the
# feed, listed it in the admin, and enforced none of it -- decorative on
# exactly the deploy mode that cannot read the maps.  The daemon now builds a
# matcher by reading back those same map files, so this drives both paths
# against one set of entries and asserts they agree.
#
# It also covers the cold-start path: admin.yml points every hub URL at a dead
# port, so the pull always fails and the ONLY way the daemon can know about an
# entry is by seeding its matcher from the files on disk at startup.  That is
# the state a real install is in whenever it restarts while unmask.sh is
# unreachable -- previously an hour-long hole on the forward-auth wire.
#
# Wires:
#   native      -> nginx container, $community_bans_hit via the rendered maps
#   forward-auth-> fa-nginx container, auth_request -> daemon matcher
#
# A ja4_only entry is what both wires can be driven with: admin.yml trusts
# X-Client-JA4 from anywhere (trusted_lb_extra 0.0.0.0/0), so the header sets
# $effective_ja4 on native and reaches the daemon on forward-auth.
#
# Two things this scenario has to arrange, both of which are real properties of
# the product rather than test scaffolding:
#
#   * The feed loop (and therefore the daemon's matcher) only starts once the
#     install wizard is done, so a box that never finished setup does not
#     register with the hub.  The stack has no user, so the scenario creates
#     one, restarts, and deletes it again.
#   * nginx parses `include`d map files at config load, so the native wire only
#     sees new entries after a RELOAD.  The daemon deliberately never reloads
#     nginx by itself, so the scenario does it -- the same thing an operator's
#     cron or the admin's "run nginx -s reload" banner does.
#
# Needs the docker e2e stack (writes the map files inside the admin container
# and restarts it).
set -u
DIR="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=../lib/env.sh
. "$DIR/lib/env.sh"
# shellcheck source=../lib/assert.sh
. "$DIR/lib/assert.sh"

COMPOSE="${COMPOSE:-$DIR/docker/docker-compose.yml}"
if ! command -v docker >/dev/null 2>&1 || \
   [ -z "$(docker compose -f "$COMPOSE" ps -q admin 2>/dev/null)" ]; then
    log_skip "58-community-bans needs the docker e2e stack (admin container) — skipped"
    exit 0
fi

fails=0

# Distinct from every other scenario's fingerprints so no verdict rule matches
# it: the ONLY thing that can challenge this client is the community feed.
JA4_LISTED="t13e2ecomm58_xxx_yyy"
JA4_CLEAN="t13e2eclean58_xxx_yyy"
MAP_DIR=/etc/unmask   # = nginx.output_dir in admin.yml; resolveMapDir falls through to it
XFF='X-Forwarded-For: 203.0.113.58'

E2E_USER=e2e-cb58
adm() { docker compose -f "$COMPOSE" exec -T --user root admin sh -c "$1" 2>/dev/null; }
ngx() { docker compose -f "$COMPOSE" exec -T --user root nginx sh -c "$1" 2>/dev/null; }

restore() {
    adm "printf '%s\n' '# generated by unmask communitybans. DO NOT EDIT.' > $MAP_DIR/community-bans-ja4.map" >/dev/null 2>&1 || true
    adm "unmask user delete $E2E_USER" >/dev/null 2>&1 || true
    docker compose -f "$COMPOSE" restart admin >/dev/null 2>&1 || true
    wait_healthz_200 >/dev/null 2>&1 || true
    # Put nginx back on an empty list so a later run starts clean.
    ngx "kill -HUP 1" >/dev/null 2>&1 || true
}
trap restore EXIT

healthz() { curl -sk -o /dev/null -w '%{http_code}' --max-time 3 "${BASE_URL}/unmask/healthz"; }
wait_healthz_200() {
    local i
    for i in $(seq 1 40); do
        [ "$(healthz)" = 200 ] && return 0
        sleep 1
    done
    return 1
}

# Pre-flight: both wires reachable, and the feed is actually enforcing (the
# rendered conf carries the maps).  Without the render the native half would
# pass by doing nothing.
if ! curl -fsS -o /dev/null --max-time 5 "${FA_NGINX_URL}/unmask/healthz"; then
    log_fail "pre-flight: ${FA_NGINX_URL}/unmask/healthz unreachable -- is the fa-nginx container up?"
    exit 1
fi
if ! adm "grep -q 'community-bans-ja4.map' $MAP_DIR/http.inc"; then
    log_fail "pre-flight: http.inc has no community-bans include -- subscribe_mode is not fetch_apply"
    exit 1
fi

# 1) Baseline BEFORE the entry exists: neither wire challenges this JA4.
body=$(curl -sk -A "$UA_BROWSER" -H "$XFF" -H "X-Client-JA4: $JA4_LISTED" "${BASE_URL}/")
assert_in "[unmask e2e]" "$body" \
    "community feed: native passes a JA4 that is not on the list yet" || fails=$((fails+1))
body=$(curl -s -A "$UA_BROWSER" -H "$XFF" -H "X-Client-JA4: $JA4_LISTED" "${FA_NGINX_URL}/")
assert_in "[fa-nginx backend]" "$body" \
    "community feed: forward-auth passes a JA4 that is not on the list yet" || fails=$((fails+1))

# 2) Publish the entry the way a pull would, then restart: the daemon must pick
#    it up from disk even though the hub is unreachable.
adm "printf '%s\n%s\n' '# generated by unmask communitybans. DO NOT EDIT.' '\"$JA4_LISTED\" 1;' > $MAP_DIR/community-bans-ja4.map" >/dev/null
if ! adm "grep -q '$JA4_LISTED' $MAP_DIR/community-bans-ja4.map"; then
    log_fail "could not write the community-bans map file"
    exit 1
fi
# Finish setup so the feed loop runs at all, then restart into it.
adm "unmask user create $E2E_USER -role admin -password cb58-$(date +%s)x" >/dev/null 2>&1
docker compose -f "$COMPOSE" restart admin >/dev/null 2>&1
if ! wait_healthz_200; then
    log_fail "admin did not come back after the restart"
    exit 1
fi
if ! adm "unmask user list" | grep -q "$E2E_USER"; then
    log_fail "could not finish setup (no user) -- the feed loop would never start"
    exit 1
fi
# nginx parses included map files at config load, so the native wire needs a
# reload before it can see the entry.  Nothing in unmask does this for the
# operator, by design.
# SIGHUP the master directly: `nginx -s reload` would look for the compiled-in
# prefix, which this image does not have (its conf is mounted elsewhere), and
# would fail silently enough to look like the feature is broken.
ngx "kill -HUP 1" >/dev/null 2>&1
sleep 3

# 3) Native: the listed JA4 is challenged, and the clean one still is not.
#    $unmask_cb_challenge is exported by the debug location, so the map lookup
#    itself is asserted rather than inferred from the page that follows it.
dbg=$(curl -sk -A "$UA_BROWSER" -H "$XFF" -H "X-Client-JA4: $JA4_LISTED" "${BASE_URL}/__unmask_debug")
assert_in "cb_challenge=1" "$dbg" \
    "community feed: native map lookup hits for a listed JA4" || fails=$((fails+1))
dbg=$(curl -sk -A "$UA_BROWSER" -H "$XFF" -H "X-Client-JA4: $JA4_CLEAN" "${BASE_URL}/__unmask_debug")
assert_in "cb_challenge=0" "$dbg" \
    "community feed: native map lookup misses for an unlisted JA4" || fails=$((fails+1))
body=$(curl -sk -A "$UA_BROWSER" -H "$XFF" -H "X-Client-JA4: $JA4_LISTED" "${BASE_URL}/")
assert_in "Security check" "$body" \
    "community feed: native challenges a listed JA4" || fails=$((fails+1))
body=$(curl -sk -A "$UA_BROWSER" -H "$XFF" -H "X-Client-JA4: $JA4_CLEAN" "${BASE_URL}/")
assert_in "[unmask e2e]" "$body" \
    "community feed: native leaves an unlisted JA4 alone" || fails=$((fails+1))

# 4) Forward-auth: the wire that used to enforce nothing.  Same entry, same
#    answer -- this is the regression that matters.
body=$(curl -s -A "$UA_BROWSER" -H "$XFF" -H "X-Client-JA4: $JA4_LISTED" "${FA_NGINX_URL}/")
assert_in "Security check" "$body" \
    "community feed: forward-auth challenges a listed JA4 (was: enforced nothing)" || fails=$((fails+1))
body=$(curl -s -A "$UA_BROWSER" -H "$XFF" -H "X-Client-JA4: $JA4_CLEAN" "${FA_NGINX_URL}/")
assert_in "[fa-nginx backend]" "$body" \
    "community feed: forward-auth leaves an unlisted JA4 alone" || fails=$((fails+1))

exit $((fails > 0 ? 1 : 0))
