// build-google-ip: Google 公式 JSON 3 種から nginx geo map 形式を生成.
//
// 取得元 (Google Search Central / Cloud 公式公開):
//
//	googlebot.json                   = Googlebot crawler
//	special-crawlers.json            = AdsBot, AdSense, Mediapartners 等
//	user-triggered-fetchers.json     = Search Console URL 検査ツール 等
//
// 出力例:
//
//	geo $is_google_ip {
//	    default 0;
//	    66.249.64.0/19  1;
//	    ...
//	}
//
// 用途: nginx の include で読まれる /etc/unmask/nginx/google-ip.conf.
// cron で 1 日 1 回 update し nginx を reload する運用.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"time"
)

// 公式 JSON は 2025 後半に /static/search/apis/ipranges/ から
// /static/crawling/ipranges/ に移動済 (= 旧 URL は "Temporarily Broken" を返す).
// 移動が起きてもユーザに 0 件配布で気づきにくいので、 旧 URL は fallback として持たない.
var googleIPSources = []string{
	"https://developers.google.com/static/crawling/ipranges/common-crawlers.json",
	"https://developers.google.com/static/crawling/ipranges/special-crawlers.json",
	"https://developers.google.com/static/crawling/ipranges/user-triggered-fetchers.json",
	"https://developers.google.com/static/crawling/ipranges/user-triggered-fetchers-google.json",
}

type googleRanges struct {
	Prefixes []struct {
		IPv4Prefix string `json:"ipv4Prefix"`
		IPv6Prefix string `json:"ipv6Prefix"`
	} `json:"prefixes"`
}

func cmdBuildGoogleIP(args []string) error {
	fs := flag.NewFlagSet("build-google-ip", flag.ExitOnError)
	out := fs.String("out", "-", "output path (- = stdout)")
	includeIPv6 := fs.Bool("ipv6", true, "include ipv6 prefixes")
	timeout := fs.Duration("timeout", 30*time.Second, "HTTP timeout")
	_ = fs.Parse(args)

	cli := &http.Client{Timeout: *timeout}
	prefixes := make([]string, 0, 4096)
	seen := map[string]bool{}

	for _, u := range googleIPSources {
		ranges, err := fetchGoogleRanges(cli, u)
		if err != nil {
			return fmt.Errorf("%s: %w", u, err)
		}
		// "Temporarily Broken" 等で prefixes が空の JSON は明確に bail. 0 件
		// 配布は災害的 (= 既存 google-ip.conf を上書きすると Googlebot が
		// challenge を踏む) なのでエラーにする.
		if len(ranges.Prefixes) == 0 {
			return fmt.Errorf("%s: 0 prefixes (upstream may have moved the URL)", u)
		}
		for _, p := range ranges.Prefixes {
			if p.IPv4Prefix != "" && !seen[p.IPv4Prefix] {
				seen[p.IPv4Prefix] = true
				prefixes = append(prefixes, p.IPv4Prefix)
			}
			if *includeIPv6 && p.IPv6Prefix != "" && !seen[p.IPv6Prefix] {
				seen[p.IPv6Prefix] = true
				prefixes = append(prefixes, p.IPv6Prefix)
			}
		}
	}
	if len(prefixes) == 0 {
		return fmt.Errorf("no prefixes collected from any source")
	}

	// sort で diff レビューしやすく.
	sort.Strings(prefixes)

	w := os.Stdout
	if *out != "-" {
		f, err := os.Create(*out)
		if err != nil {
			return err
		}
		defer f.Close()
		w = f
	}

	fmt.Fprintf(w, "# generated by unmask-admin build-google-ip at %s\n",
		time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintln(w, "# DO NOT EDIT BY HAND. re-run the command to refresh.")
	fmt.Fprintln(w, "geo $is_google_ip {")
	fmt.Fprintln(w, "    default 0;")
	for _, p := range prefixes {
		fmt.Fprintf(w, "    %-22s 1;\n", p)
	}
	fmt.Fprintln(w, "}")
	if *out != "-" {
		fmt.Fprintf(os.Stderr, "wrote %d prefixes to %s\n", len(prefixes), *out)
	}
	return nil
}

func fetchGoogleRanges(cli *http.Client, url string) (*googleRanges, error) {
	req, _ := http.NewRequest(http.MethodGet, url, nil)
	req.Header.Set("User-Agent", "unmask-admin/"+Version)
	resp, err := cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("status %d", resp.StatusCode)
	}
	body, err := io.ReadAll(io.LimitReader(resp.Body, 2*1024*1024))
	if err != nil {
		return nil, err
	}
	var r googleRanges
	if err := json.Unmarshal(body, &r); err != nil {
		return nil, fmt.Errorf("decode: %w", err)
	}
	return &r, nil
}
