// Regression tests for the community-bans map placeholders that Render must lay
// down whenever http.inc `include`s them.  Without these, a fresh install's
// `unmask render-nginx` (postinstall) emits an http.inc that `nginx -t` rejects
// with "open() .../community-bans-*.map failed" until the admin daemon's first
// community-bans tick -- breaking nginx reload/restart on the box.
package nginxconf

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/unmask-sh/unmask/admin/internal/settings"
)

func TestEnsureCommunityBanMapPlaceholders(t *testing.T) {
	dir := t.TempDir()

	// 1. all 3 placeholders are created when absent.
	ensureCommunityBanMapPlaceholders(dir)
	for _, name := range communityBanMapFiles {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Fatalf("placeholder %s not created: %v", name, err)
		}
	}

	// 2. a populated map is never clobbered (O_EXCL).
	populated := filepath.Join(dir, "community-bans-ipja4.map")
	want := []byte("# generated by unmask communitybans. DO NOT EDIT.\n\"1.2.3.4:t13d\" 1;\n")
	if err := os.WriteFile(populated, want, 0o644); err != nil {
		t.Fatal(err)
	}
	ensureCommunityBanMapPlaceholders(dir)
	got, err := os.ReadFile(populated)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != string(want) {
		t.Fatalf("populated map clobbered:\n got: %q\nwant: %q", got, want)
	}
}

func TestRenderLaysCommunityBanPlaceholders(t *testing.T) {
	// fetch_apply: http.inc includes the maps, so Render must create them.
	t.Run("fetch_apply_creates", func(t *testing.T) {
		dir := t.TempDir()
		// Render now probes nginx.conf for an existing map_hash; point it at a
		// controlled empty conf so the test doesn't depend on the host's /etc/nginx.
		conf := filepath.Join(dir, "nginx.conf")
		if err := os.WriteFile(conf, []byte("http {\n}\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		var s settings.Settings
		s.Nginx.OutputDir = dir
		s.Nginx.ConfPath = conf
		s.CommunityBans.SubscribeMode = settings.SubscribeFetchApply
		if err := Render(s, dir, "test"); err != nil {
			t.Fatalf("Render: %v", err)
		}
		for _, name := range communityBanMapFiles {
			if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
				t.Errorf("Render did not lay placeholder %s: %v", name, err)
			}
		}
	})

	// off: no include emitted, so no placeholder should appear.
	t.Run("off_creates_none", func(t *testing.T) {
		dir := t.TempDir()
		var s settings.Settings
		s.Nginx.OutputDir = dir
		s.CommunityBans.SubscribeMode = settings.SubscribeOff
		if err := Render(s, dir, "test"); err != nil {
			t.Fatalf("Render: %v", err)
		}
		for _, name := range communityBanMapFiles {
			if _, err := os.Stat(filepath.Join(dir, name)); err == nil {
				t.Errorf("Render created %s in off mode (should not)", name)
			}
		}
	})
}
